import {
  expandedThemesData,
  expandedThemeGroups,
  expandedThemeEmoji,
} from "./iconDataExpanded";

export interface ThemeIcon {
  id: string;
  name: string;
  lucideName: string; // PascalCase name to import from lucide-react
  desc: string;
  defaultBadge?: string;
  defaultGradient: [string, string];
}

export interface Theme {
  id: string;
  name: string;
  englishName: string;
  description: string;
  icon: string; // Representative Lucide icon name for the theme
  icons: ThemeIcon[];
}

export const PRESET_GRADIENTS: { name: string; colors: [string, string] }[] = [
  { name: "极光蓝", colors: ["#3b82f6", "#1d4ed8"] },
  { name: "森林绿", colors: ["#10b981", "#047857"] },
  { name: "落日橙", colors: ["#f97316", "#ea580c"] },
  { name: "霓虹紫", colors: ["#8b5cf6", "#6d28d9"] },
  { name: "科技青", colors: ["#06b6d4", "#0891b2"] },
  { name: "樱花粉", colors: ["#ec4899", "#be185d"] },
  { name: "炙热红", colors: ["#ef4444", "#b91c1c"] },
  { name: "琥珀黄", colors: ["#f59e0b", "#d97706"] },
  { name: "宇宙灰", colors: ["#64748b", "#334155"] },
  { name: "深邃黑", colors: ["#1e293b", "#0f172a"] },
  { name: "极客蓝", colors: ["#60a5fa", "#3b82f6"] },
  { name: "梦幻紫", colors: ["#d946ef", "#a21caf"] },
];

const baseThemesData: Theme[] = [
  {
    id: "system",
    name: "系统与工具",
    englishName: "System & Tools",
    description: "经典系统操作与基础工具图标",
    icon: "Settings",
    icons: [
      { id: "sys-1", name: "文件管理器", lucideName: "Folder", desc: "管理和整理文件", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "sys-2", name: "系统设置", lucideName: "Settings", desc: "配置您的系统", defaultGradient: ["#64748b", "#334155"] },
      { id: "sys-3", name: "终端命令行", lucideName: "Terminal", desc: "执行系统命令", defaultGradient: ["#1e293b", "#0f172a"], defaultBadge: "Dev" },
      { id: "sys-4", name: "中央处理器", lucideName: "Cpu", desc: "系统核心硬件", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sys-5", name: "数据库", lucideName: "Database", desc: "数据存储管理", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "sys-6", name: "本地硬盘", lucideName: "HardDrive", desc: "物理存储设备", defaultGradient: ["#64748b", "#475569"] },
      { id: "sys-7", name: "垃圾桶", lucideName: "Trash2", desc: "清理临时文件", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "sys-8", name: "安全防护", lucideName: "Shield", desc: "防御恶意软件", defaultGradient: ["#10b981", "#047857"], defaultBadge: "安全" },
      { id: "sys-9", name: "系统信息", lucideName: "Info", desc: "查看版本与状态", defaultGradient: ["#3b82f6", "#2563eb"] },
      { id: "sys-10", name: "电源控制", lucideName: "Power", desc: "关机、重启与睡眠", defaultGradient: ["#ef4444", "#dc2626"] },
    ],
  },
  {
    id: "office",
    name: "办公与效率",
    englishName: "Office & Productivity",
    description: "高效办公与个人生产力辅助工具",
    icon: "Briefcase",
    icons: [
      { id: "off-1", name: "文本文档", lucideName: "FileText", desc: "编辑与管理文本", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "off-2", name: "日历行程", lucideName: "Calendar", desc: "规划日程与会议", defaultGradient: ["#ef4444", "#c2410c"], defaultBadge: "新" },
      { id: "off-3", name: "电子邮件", lucideName: "Mail", desc: "收发重要信件", defaultGradient: ["#f57c00", "#d84315"] },
      { id: "off-4", name: "画图钢笔", lucideName: "PenTool", desc: "矢量图形编辑", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "off-5", name: "剪贴板", lucideName: "Clipboard", desc: "历史复制记录", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "off-6", name: "文档编辑", lucideName: "Edit", desc: "修改文章或代码", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "off-7", name: "打印机", lucideName: "Printer", desc: "纸张文档输出", defaultGradient: ["#64748b", "#334155"] },
      { id: "off-8", name: "计算器", lucideName: "Calculator", desc: "数值公式计算", defaultGradient: ["#10b981", "#059669"] },
      { id: "off-9", name: "归档管理器", lucideName: "Archive", desc: "压缩与备份文件", defaultGradient: ["#f59e0b", "#b45309"] },
      { id: "off-10", name: "待办清单", lucideName: "CheckSquare", desc: "任务打卡记录", defaultGradient: ["#10b981", "#047857"] },
    ],
  },
  {
    id: "social",
    name: "社交与通讯",
    englishName: "Social & Chat",
    description: "人际交往与即时聊天工具",
    icon: "MessageSquare",
    icons: [
      { id: "soc-1", name: "气泡聊天", lucideName: "MessageSquare", desc: "一对一文字聊天", defaultGradient: ["#10b981", "#059669"] },
      { id: "soc-2", name: "圈子群聊", lucideName: "MessageCircle", desc: "多人社交群组", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "soc-3", name: "语音电话", lucideName: "Phone", desc: "高质量语音通话", defaultGradient: ["#10b981", "#047857"] },
      { id: "soc-4", name: "视频会议", lucideName: "Video", desc: "在线视频通话", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "soc-5", name: "联系人", lucideName: "Users", desc: "管理好友和同事", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "soc-6", name: "分享转发", lucideName: "Share2", desc: "传播内容到外部", defaultGradient: ["#64748b", "#475569"] },
      { id: "soc-7", name: "收藏喜欢", lucideName: "Heart", desc: "标记感兴趣的内容", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "soc-8", name: "发送传送", lucideName: "Send", desc: "即时投递消息", defaultGradient: ["#3b82f6", "#2563eb"] },
      { id: "soc-9", name: "系统通知", lucideName: "Bell", desc: "接收最新提醒", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "soc-10", name: "成就奖章", lucideName: "Award", desc: "社交荣誉和认证", defaultGradient: ["#eab308", "#a16207"], defaultBadge: "VIP" },
    ],
  },
  {
    id: "design",
    name: "创意与设计",
    englishName: "Design & Creative",
    description: "设计师不可缺少的创意工具图标",
    icon: "Palette",
    icons: [
      { id: "des-1", name: "调色板", lucideName: "Palette", desc: "搭配与编辑色彩", defaultGradient: ["#ec4899", "#a21caf"] },
      { id: "des-2", name: "创意画笔", lucideName: "Paintbrush", desc: "手绘插画与涂鸦", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "des-3", name: "图层管理", lucideName: "Layers", desc: "叠加与组织元素", defaultGradient: ["#3b82f6", "#1d4ed8"], defaultBadge: "Pro" },
      { id: "des-4", name: "裁剪工具", lucideName: "Crop", desc: "限定画布大小", defaultGradient: ["#64748b", "#334155"] },
      { id: "des-5", name: "剪刀", lucideName: "Scissors", desc: "精细拆分与裁剪", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "des-6", name: "图片画廊", lucideName: "Image", desc: "浏览与导入底图", defaultGradient: ["#10b981", "#059669"] },
      { id: "des-7", name: "相机镜头", lucideName: "Camera", desc: "高清拍摄记录", defaultGradient: ["#475569", "#1e293b"] },
      { id: "des-8", name: "指南针", lucideName: "Compass", desc: "探索设计方向", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "des-9", name: "预览视窗", lucideName: "Eye", desc: "查看最终渲染图", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "des-10", name: "羽毛笔", lucideName: "PenTool", desc: "经典拟物书写", defaultGradient: ["#f59e0b", "#b45309"] },
    ],
  },
  {
    id: "coding",
    name: "开发与编程",
    englishName: "Coding & Dev",
    description: "专为程序员量身定制的开发工具图标",
    icon: "Code2",
    icons: [
      { id: "cod-1", name: "代码编辑器", lucideName: "Code2", desc: "编写与重构代码", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "cod-2", name: "命令终端", lucideName: "Terminal", desc: "快速开发控制台", defaultGradient: ["#1e293b", "#0f172a"] },
      { id: "cod-3", name: "代码分支", lucideName: "GitBranch", desc: "创建功能与合并", defaultGradient: ["#10b981", "#047857"] },
      { id: "cod-4", name: "代码提交", lucideName: "GitCommit", desc: "保存历史版本", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "cod-5", name: "合并请求", lucideName: "GitPullRequest", desc: "代码审核与发布", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "cod-6", name: "云端服务器", lucideName: "Server", desc: "托管后台程序", defaultGradient: ["#64748b", "#334155"] },
      { id: "cod-7", name: "插件模块", lucideName: "Blocks", desc: "积木式拓展功能", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "cod-8", name: "括号语法", lucideName: "Code2", desc: "语法规范检测", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "cod-9", name: "程序漏洞", lucideName: "Bug", desc: "定位调试代码", defaultGradient: ["#ef4444", "#b91c1c"], defaultBadge: "Debug" },
      { id: "cod-10", name: "硬件芯片", lucideName: "Cpu", desc: "单片机与处理器", defaultGradient: ["#8b5cf6", "#6d28d9"] },
    ],
  },
  {
    id: "network",
    name: "网络与通信",
    englishName: "Network & Signal",
    description: "各种网络连接与信号传输图标",
    icon: "Wifi",
    icons: [
      { id: "net-1", name: "无线网络", lucideName: "Wifi", desc: "无线上网连接", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "net-2", name: "蓝牙", lucideName: "Bluetooth", desc: "无线近场传输", defaultGradient: ["#2563eb", "#1d4ed8"] },
      { id: "net-3", name: "广播电台", lucideName: "Radio", desc: "无线频段广播", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "net-4", name: "网盘云盘", lucideName: "Cloud", desc: "文件实时上云", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "net-5", name: "全球互联", lucideName: "Globe", desc: "万维网国际连接", defaultGradient: ["#10b981", "#059669"] },
      { id: "net-6", name: "超链接", lucideName: "Link", desc: "网址页面跳转", defaultGradient: ["#64748b", "#475569"] },
      { id: "net-7", name: "有线网络", lucideName: "Router", desc: "以太网物理连接", defaultGradient: ["#334155", "#0f172a"] },
      { id: "net-8", name: "无线投屏", lucideName: "Tv", desc: "投屏到电视大屏", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "net-9", name: "数据下载", lucideName: "CloudDownload", desc: "拉取云端资源", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "net-10", name: "路由器", lucideName: "Router", desc: "网络分发设备", defaultGradient: ["#64748b", "#334155"] },
    ],
  },
  {
    id: "security",
    name: "安全与隐私",
    englishName: "Security & Safety",
    description: "数据加密与安全认证图标",
    icon: "Shield",
    icons: [
      { id: "sec-1", name: "安全锁", lucideName: "Lock", desc: "加密和保护信息", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "sec-2", name: "开锁", lucideName: "Unlock", desc: "解锁权限受限", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "sec-3", name: "盾牌保护", lucideName: "Shield", desc: "主动防御检测", defaultGradient: ["#10b981", "#047857"] },
      { id: "sec-4", name: "安全验证", lucideName: "ShieldCheck", desc: "防篡改验证成功", defaultGradient: ["#10b981", "#059669"] },
      { id: "sec-5", name: "密钥", lucideName: "Key", desc: "解密私钥数据", defaultGradient: ["#f59e0b", "#b45309"] },
      { id: "sec-6", name: "隐藏密码", lucideName: "EyeOff", desc: "输入隐私保护", defaultGradient: ["#64748b", "#334155"] },
      { id: "sec-7", name: "指纹识别", lucideName: "Fingerprint", desc: "生物特征登录", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sec-8", name: "扫码识别", lucideName: "Scan", desc: "摄像头条码扫描", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "sec-9", name: "安全警报", lucideName: "ShieldAlert", desc: "异常行为警告", defaultGradient: ["#ef4444", "#b91c1c"], defaultBadge: "告警" },
      { id: "sec-10", name: "密钥文件", lucideName: "FileKey", desc: "加密证书私钥", defaultGradient: ["#8b5cf6", "#4c1d95"] },
    ],
  },
  {
    id: "finance",
    name: "商业与金融",
    englishName: "Finance & Commerce",
    description: "适用于记账、交易和企业管理的图标",
    icon: "CreditCard",
    icons: [
      { id: "fin-1", name: "银行卡", lucideName: "CreditCard", desc: "在线刷卡支付", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "fin-2", name: "电子钱包", lucideName: "Wallet", desc: "零钱收支管理", defaultGradient: ["#f59e0b", "#b45309"] },
      { id: "fin-3", name: "金币", lucideName: "Coins", desc: "积分与虚拟代币", defaultGradient: ["#eab308", "#a16207"] },
      { id: "fin-4", name: "美元", lucideName: "DollarSign", desc: "财务外汇交易", defaultGradient: ["#10b981", "#047857"] },
      { id: "fin-5", name: "趋势增长", lucideName: "TrendingUp", desc: "利润与流量分析", defaultGradient: ["#10b981", "#059669"], defaultBadge: "HOT" },
      { id: "fin-6", name: "购物车", lucideName: "ShoppingCart", desc: "下单结算宝贝", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "fin-7", name: "购物袋", lucideName: "ShoppingBag", desc: "买单外卖包装", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "fin-8", name: "金融银行", lucideName: "Landmark", desc: "实体金融网点", defaultGradient: ["#64748b", "#334155"] },
      { id: "fin-9", name: "卓越奖杯", lucideName: "Trophy", desc: "销售冠军奖励", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "fin-10", name: "路演简报", lucideName: "Presentation", desc: "商业计划演讲", defaultGradient: ["#8b5cf6", "#6d28d9"] },
    ],
  },
  {
    id: "media",
    name: "媒体与影音",
    englishName: "Media & Audio",
    description: "视频播放与音频控制相关图标",
    icon: "Play",
    icons: [
      { id: "med-1", name: "播放", lucideName: "Play", desc: "开始播放音视频", defaultGradient: ["#10b981", "#059669"] },
      { id: "med-2", name: "暂停", lucideName: "Pause", desc: "暂停当前项目", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "med-3", name: "下一首", lucideName: "SkipForward", desc: "跳过并播放下一条", defaultGradient: ["#64748b", "#334155"] },
      { id: "med-4", name: "上一首", lucideName: "SkipBack", desc: "返回上一条曲目", defaultGradient: ["#64748b", "#334155"] },
      { id: "med-5", name: "音乐音符", lucideName: "Music", desc: "播放本地音频", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "med-6", name: "扬声器", lucideName: "Volume2", desc: "调节声音大小", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "med-7", name: "麦克风", lucideName: "Mic", desc: "录音与语音输入", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "med-8", name: "电影胶片", lucideName: "Film", desc: "录像与影视剪辑", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "med-9", name: "唱片黑胶", lucideName: "Disc", desc: "无损复古唱片", defaultGradient: ["#1e293b", "#0f172a"] },
      { id: "med-10", name: "无线电收音", lucideName: "Radio", desc: "调频调幅电台", defaultGradient: ["#f59e0b", "#b45309"] },
    ],
  },
  {
    id: "smarthome",
    name: "智能家居",
    englishName: "Smart Home",
    description: "万物互联的家庭设备控制图标",
    icon: "Home",
    icons: [
      { id: "hom-1", name: "主页", lucideName: "Home", desc: "返回大本营", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "hom-2", name: "智能灯泡", lucideName: "Lightbulb", desc: "开关灯光色彩", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "hom-3", name: "温控器", lucideName: "Thermometer", desc: "调节室内温度", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "hom-4", name: "智能锁", lucideName: "Lock", desc: "家庭入户安防", defaultGradient: ["#10b981", "#047857"] },
      { id: "hom-5", name: "摄像头", lucideName: "Video", desc: "实时看家监控", defaultGradient: ["#64748b", "#334155"] },
      { id: "hom-6", name: "智能插座", lucideName: "Plug", desc: "电源耗电量统计", defaultGradient: ["#10b981", "#059669"] },
      { id: "hom-7", name: "风扇空气净化", lucideName: "Wind", desc: "室内新风控制", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "hom-8", name: "家庭WiFi", lucideName: "Wifi", desc: "局域网状态", defaultGradient: ["#3b82f6", "#2563eb"] },
      { id: "hom-9", name: "门铃提醒", lucideName: "Bell", desc: "访客按门铃通知", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "hom-10", name: "智能电视", lucideName: "Tv", desc: "大屏电视互动", defaultGradient: ["#8b5cf6", "#6d28d9"] },
    ],
  },
  {
    id: "health",
    name: "运动与健康",
    englishName: "Health & Fitness",
    description: "记录跑步、卡路里与健康体征的图标",
    icon: "Activity",
    icons: [
      { id: "hea-1", name: "爱心指数", lucideName: "Heart", desc: "关爱与喜欢度", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "hea-2", name: "心电图", lucideName: "Activity", desc: "实时心率变异率", defaultGradient: ["#ef4444", "#dc2626"] },
      { id: "hea-3", name: "卡路里燃烧", lucideName: "Flame", desc: "今日消耗热量", defaultGradient: ["#f97316", "#c2410c"], defaultBadge: "火" },
      { id: "hea-4", name: "荣誉奖杯", lucideName: "Trophy", desc: "超越自我的挑战", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "hea-5", name: "每日足迹", lucideName: "Footprints", desc: "计算跑步与步数", defaultGradient: ["#10b981", "#047857"] },
      { id: "hea-6", name: "健身哑铃", lucideName: "Dumbbell", desc: "力量抗阻训练", defaultGradient: ["#64748b", "#334155"] },
      { id: "hea-7", name: "水分补充", lucideName: "Droplet", desc: "提示定时喝水", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "hea-8", name: "健康餐水果", lucideName: "Apple", desc: "膳食营养配比", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "hea-9", name: "胶囊药丸", lucideName: "Pill", desc: "定时服药小助手", defaultGradient: ["#ef4444", "#22c55e"] },
      { id: "hea-10", name: "舒适日光", lucideName: "Sun", desc: "早起晨跑与日晒", defaultGradient: ["#f59e0b", "#d97706"] },
    ],
  },
  {
    id: "travel",
    name: "旅游与交通",
    englishName: "Travel & Maps",
    description: "地图出行、机酒与出境游图标",
    icon: "Map",
    icons: [
      { id: "tra-1", name: "世界地图", lucideName: "Map", desc: "查看国家与路线", defaultGradient: ["#10b981", "#059669"] },
      { id: "tra-2", name: "地图图钉", lucideName: "MapPin", desc: "目标精确定位", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "tra-3", name: "指南针", lucideName: "Compass", desc: "野外确定方向", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "tra-4", name: "导航定位", lucideName: "Navigation", desc: "实时GPS路径规划", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "tra-5", name: "飞机出境", lucideName: "Plane", desc: "国际航班值机", defaultGradient: ["#3b82f6", "#1d4ed8"], defaultBadge: "特价" },
      { id: "tra-6", name: "火车高铁", lucideName: "Train", desc: "省际高速铁路", defaultGradient: ["#10b981", "#047857"] },
      { id: "tra-7", name: "自驾小车", lucideName: "Car", desc: "本地租车出行", defaultGradient: ["#64748b", "#334155"] },
      { id: "tra-8", name: "行李箱", lucideName: "Luggage", desc: "收拾远行装备", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "tra-9", name: "酒店住宿", lucideName: "Home", desc: "精选客栈民居", defaultGradient: ["#f59e0b", "#b45309"] },
      { id: "tra-10", name: "公事出差", lucideName: "Briefcase", desc: "商务旅行装备", defaultGradient: ["#64748b", "#475569"] },
    ],
  },
  {
    id: "science",
    name: "教育与科学",
    englishName: "Science & Education",
    description: "实验、数学研究及学校教育图标",
    icon: "GraduationCap",
    icons: [
      { id: "sci-1", name: "阅读课本", lucideName: "BookOpen", desc: "学习新知识", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "sci-2", name: "毕业帽", lucideName: "GraduationCap", desc: "学位与学术研究", defaultGradient: ["#6d28d9", "#4c1d95"] },
      { id: "sci-3", name: "显微镜", lucideName: "Microscope", desc: "观测微观结构", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "sci-4", name: "原子结构", lucideName: "Atom", desc: "物理化学概念", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sci-5", name: "地球仪", lucideName: "Globe", desc: "地理空间课", defaultGradient: ["#10b981", "#059669"] },
      { id: "sci-6", name: "教学比例尺", lucideName: "Ruler", desc: "几何与精准画线", defaultGradient: ["#64748b", "#334155"] },
      { id: "sci-7", name: "公式计算器", lucideName: "Calculator", desc: "函数与金融算法", defaultGradient: ["#10b981", "#047857"] },
      { id: "sci-8", name: "烧杯试管", lucideName: "FlaskConical", desc: "实验室化学反应", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "sci-9", name: "指南罗盘", lucideName: "Compass", desc: "逻辑思维发散", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "sci-10", name: "特等奖状", lucideName: "Award", desc: "学术卓越证书", defaultGradient: ["#eab308", "#ca8a04"] },
    ],
  },
  {
    id: "nature",
    name: "自然与天气",
    englishName: "Nature & Weather",
    description: "四季变换与森林植被环保图标",
    icon: "Sun",
    icons: [
      { id: "nat-1", name: "绿叶环保", lucideName: "Leaf", desc: "绿色碳中和", defaultGradient: ["#10b981", "#047857"] },
      { id: "nat-2", name: "花朵绽放", lucideName: "Flower", desc: "生命力与设计", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "nat-3", name: "晴朗太阳", lucideName: "Sun", desc: "阳光明媚天气", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "nat-4", name: "下雨云朵", lucideName: "CloudRain", desc: "多雨降水天气", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "nat-5", name: "雪花冰冻", lucideName: "CloudSnow", desc: "极寒飘雪冰雹", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "nat-6", name: "雷阵雨", lucideName: "CloudLightning", desc: "雷暴强降水", defaultGradient: ["#f59e0b", "#475569"] },
      { id: "nat-7", name: "明月夜空", lucideName: "Moon", desc: "安睡月亮星辰", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "nat-8", name: "狂风呼啸", lucideName: "Wind", desc: "大风沙尘气旋", defaultGradient: ["#64748b", "#334155"] },
      { id: "nat-9", name: "绿树成荫", lucideName: "Trees", desc: "森林植被公园", defaultGradient: ["#10b981", "#065f46"] },
      { id: "nat-10", name: "清澈露珠", lucideName: "Droplets", desc: "高纯度天然矿泉", defaultGradient: ["#38bdf8", "#0284c7"] },
    ],
  },
  {
    id: "gaming",
    name: "游戏与娱乐",
    englishName: "Gaming & Fun",
    description: "休闲玩乐与竞技游戏图标",
    icon: "Gamepad2",
    icons: [
      { id: "gam-1", name: "手柄游戏", lucideName: "Gamepad2", desc: "主机格斗竞速", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "gam-2", name: "随机骰子", lucideName: "Dices", desc: "桌游决定点数", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "gam-3", name: "拼图解密", lucideName: "Puzzle", desc: "思维逻辑拼接", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "gam-4", name: "闪耀星星", lucideName: "Star", desc: "关卡评分与五星", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "gam-5", name: "大礼包", lucideName: "Gift", desc: "游戏福利礼包", defaultGradient: ["#ef4444", "#b91c1c"], defaultBadge: "免费" },
      { id: "gam-6", name: "尊贵皇冠", lucideName: "Crown", desc: "排行榜霸榜皇冠", defaultGradient: ["#eab308", "#a16207"] },
      { id: "gam-7", name: "格斗长剑", lucideName: "Sword", desc: "魔幻动作对决", defaultGradient: ["#ef4444", "#7f1d1d"] },
      { id: "gam-8", name: "精准射击", lucideName: "Target", desc: "命中靶心目标", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "gam-9", name: "幸运草", lucideName: "Clover", desc: "抽卡好运加持", defaultGradient: ["#10b981", "#047857"] },
      { id: "gam-10", name: "大奖赛", lucideName: "Trophy", desc: "电子竞技锦标赛", defaultGradient: ["#eab308", "#b45309"] },
    ],
  },
  {
    id: "ai",
    name: "智能与科技",
    englishName: "AI & Technology",
    description: "前沿人工智能与深度学习图标",
    icon: "Brain",
    icons: [
      { id: "ai-1", name: "AI大脑", lucideName: "Brain", desc: "神经网络智能", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "ai-2", name: "AI助手", lucideName: "Bot", desc: "对话机器人小AI", defaultGradient: ["#06b6d4", "#0891b2"], defaultBadge: "AI" },
      { id: "ai-3", name: "魔法火花", lucideName: "Sparkles", desc: "AI一键生成美化", defaultGradient: ["#d946ef", "#86198f"] },
      { id: "ai-4", name: "计算芯片", lucideName: "Cpu", desc: "GPU高性能算力", defaultGradient: ["#64748b", "#334155"] },
      { id: "ai-5", name: "高频信号", lucideName: "Wifi", desc: "极速宽带无线传输", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ai-6", name: "天线基站", lucideName: "Radio", desc: "5G毫米波网络", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ai-7", name: "闪电充能", lucideName: "Zap", desc: "超低延迟算力爆发", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "ai-8", name: "实时迭代", lucideName: "RefreshCw", desc: "模型参数自适应", defaultGradient: ["#10b981", "#059669"] },
      { id: "ai-9", name: "边缘雷达", lucideName: "Radar", desc: "三维空间识别感知", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "ai-10", name: "二进制数据", lucideName: "Binary", desc: "字节与机器代码", defaultGradient: ["#1e293b", "#0f172a"] },
    ],
  },
  {
    id: "food",
    name: "美食与餐饮",
    englishName: "Food & Beverage",
    description: "休闲小吃、咖啡与美味烹饪图标",
    icon: "Coffee",
    icons: [
      { id: "foo-1", name: "提神咖啡", lucideName: "Coffee", desc: "意式浓缩与拿铁", defaultGradient: ["#b45309", "#78350f"] },
      { id: "foo-2", name: "美味披萨", lucideName: "Pizza", desc: "意式双拼芝士披萨", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "foo-3", name: "营养热汤", lucideName: "Soup", desc: "慢炖蔬菜排骨汤", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "foo-4", name: "葡萄酒", lucideName: "Wine", desc: "红酒聚会高脚杯", defaultGradient: ["#ef4444", "#7f1d1d"] },
      { id: "foo-5", name: "甜品蛋糕", lucideName: "Cake", desc: "草莓生日小蛋糕", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "foo-6", name: "新鲜苹果", lucideName: "Apple", desc: "健康低卡苹果", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "foo-7", name: "精酿啤酒", lucideName: "Beer", desc: "冰镇大扎小麦啤酒", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "foo-8", name: "果汁白水", lucideName: "GlassWater", desc: "无气泡柠檬纯净水", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "foo-9", name: "冰淇淋", lucideName: "IceCream", desc: "双色双球冰淇淋", defaultGradient: ["#ec4899", "#a21caf"] },
      { id: "foo-10", name: "大厨帽子", lucideName: "ChefHat", desc: "专业名厨烹饪指南", defaultGradient: ["#64748b", "#334155"] },
    ],
  },
  {
    id: "devices",
    name: "设备与硬件",
    englishName: "Devices & Hardware",
    description: "数码电子及计算机外设图标",
    icon: "Smartphone",
    icons: [
      { id: "dev-1", name: "智能手机", lucideName: "Smartphone", desc: "随身智能终端设备", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "dev-2", name: "平板电脑", lucideName: "Tablet", desc: "便携大屏影音板", defaultGradient: ["#64748b", "#334155"] },
      { id: "dev-3", name: "笔记本", lucideName: "Laptop", desc: "移动生产力办公本", defaultGradient: ["#1e293b", "#0f172a"] },
      { id: "dev-4", name: "高刷显示器", lucideName: "Monitor", desc: "桌面显示终端", defaultGradient: ["#3b82f6", "#2563eb"] },
      { id: "dev-5", name: "智能手表", lucideName: "Watch", desc: "运动睡眠监测表", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "dev-6", name: "无线鼠标", lucideName: "Mouse", desc: "人体工学办公鼠标", defaultGradient: ["#64748b", "#475569"] },
      { id: "dev-7", name: "机械键盘", lucideName: "Keyboard", desc: "全键无冲红轴键盘", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "dev-8", name: "打印机设备", lucideName: "Printer", desc: "多功能彩色打印机", defaultGradient: ["#64748b", "#334155"] },
      { id: "dev-9", name: "头戴式耳机", lucideName: "Headphones", desc: "主动降噪蓝牙耳机", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "dev-10", name: "重低音音箱", lucideName: "Speaker", desc: "智能重低音蓝牙箱", defaultGradient: ["#06b6d4", "#0891b2"] },
    ],
  },
  {
    id: "archives",
    name: "文件与整理",
    englishName: "Files & Archive",
    description: "高效的办公文档分类与归档图标",
    icon: "FolderOpen",
    icons: [
      { id: "arc-1", name: "文件夹", lucideName: "Folder", desc: "整理电脑归档目录", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "arc-2", name: "展开文件夹", lucideName: "FolderOpen", desc: "当前展开的子目录", defaultGradient: ["#3b82f6", "#2563eb"] },
      { id: "arc-3", name: "空白文档", lucideName: "File", desc: "新建无格式子文件", defaultGradient: ["#64748b", "#475569"] },
      { id: "arc-4", name: "多文档堆叠", lucideName: "Files", desc: "批量导入多个文件", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "arc-5", name: "收件箱", lucideName: "Inbox", desc: "接收日常代办文件", defaultGradient: ["#f59e0b", "#b45309"] },
      { id: "arc-6", name: "减少文件", lucideName: "FileMinus", desc: "删除指定行和段落", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "arc-7", name: "添加文件", lucideName: "FilePlus", desc: "新建配置或者代码", defaultGradient: ["#10b981", "#047857"] },
      { id: "arc-8", name: "归档备份箱", lucideName: "Archive", desc: "存放历史弃用文件", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "arc-9", name: "卡片叠加", lucideName: "Layers", desc: "分块归档和叠放", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "arc-10", name: "图书阅览室", lucideName: "Library", desc: "分类清晰的书架", defaultGradient: ["#8b5cf6", "#4c1d95"] },
    ],
  },
  {
    id: "deals",
    name: "购物与折扣",
    englishName: "Shopping & Deals",
    description: "适用于电商平台的满减折扣和活动图标",
    icon: "Tag",
    icons: [
      { id: "dea-1", name: "购物车", lucideName: "ShoppingCart", desc: "添加意向购买宝贝", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "dea-2", name: "精美礼品", lucideName: "Gift", desc: "生日赠送大礼包", defaultGradient: ["#ef4444", "#dc2626"], defaultBadge: "礼" },
      { id: "dea-3", name: "优惠吊牌", lucideName: "Tag", desc: "商品单价折扣吊牌", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "dea-4", name: "游园入场券", lucideName: "Ticket", desc: "电影与游乐场代金券", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "dea-5", name: "百分比折扣", lucideName: "Percent", desc: "限时秒杀打折力度", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "dea-6", name: "代金金币", lucideName: "Coins", desc: "签到赠送购物代币", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "dea-7", name: "收藏好评", lucideName: "Star", desc: "给掌柜五星好评", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "dea-8", name: "连锁实体店", lucideName: "Store", desc: "线下精选体验店铺", defaultGradient: ["#64748b", "#334155"] },
      { id: "dea-9", name: "快递包裹", lucideName: "Package", desc: "发货与转运箱包装", defaultGradient: ["#b45309", "#78350f"] },
      { id: "dea-10", name: "支付成功", lucideName: "CheckCircle", desc: "订单扣款结算完成", defaultGradient: ["#10b981", "#059669"] },
    ],
  },
];

export const themesData: Theme[] = [...baseThemesData, ...expandedThemesData];

export interface ThemeGroup {
  id: string;
  name: string;
  emoji: string;
  themeIds: string[];
}

export const THEME_EMOJI: Record<string, string> = {
  system: "⚙️",
  office: "💼",
  social: "💬",
  design: "🎨",
  coding: "💻",
  network: "🌐",
  security: "🛡️",
  finance: "💳",
  media: "🎬",
  smarthome: "🏠",
  health: "❤️",
  travel: "🗺️",
  science: "🎓",
  nature: "🌲",
  gaming: "🎮",
  ai: "🤖",
  food: "☕",
  devices: "📱",
  archives: "📁",
  deals: "🏷️",
  ...expandedThemeEmoji,
};

/** 将子主题整合为侧边栏大类 */
export const themeGroups: ThemeGroup[] = [
  {
    id: "tech",
    name: "科技与开发",
    emoji: "💻",
    themeIds: ["system", "coding", "network", "security", "ai", "devices"],
  },
  {
    id: "work",
    name: "办公与商业",
    emoji: "💼",
    themeIds: ["office", "archives", "finance", "deals"],
  },
  {
    id: "connect",
    name: "社交与媒体",
    emoji: "💬",
    themeIds: ["social", "media"],
  },
  {
    id: "creative",
    name: "创意与娱乐",
    emoji: "🎨",
    themeIds: ["design", "gaming"],
  },
  {
    id: "life",
    name: "生活与出行",
    emoji: "🏡",
    themeIds: ["smarthome", "health", "travel", "food"],
  },
  {
    id: "nature-science",
    name: "自然与教育",
    emoji: "🌿",
    themeIds: ["science", "nature"],
  },
  ...expandedThemeGroups,
];

export function getThemeGroupId(themeId: string): string | undefined {
  return themeGroups.find((g) => g.themeIds.includes(themeId))?.id;
}

// Keyword to Lucide component map for search-to-icon queries
export const keywordToIconMap: Record<string, { lucideName: string; name: string; desc: string }> = {
  // English words
  lock: { lucideName: "Lock", name: "自定义安全锁", desc: "根据您输入的词条随机生成" },
  unlock: { lucideName: "Unlock", name: "自定义解锁键", desc: "根据您输入的词条随机生成" },
  cloud: { lucideName: "Cloud", name: "云端网络", desc: "根据您输入的词条随机生成" },
  database: { lucideName: "Database", name: "数据库", desc: "根据您输入的词条随机生成" },
  settings: { lucideName: "Settings", name: "全局配置", desc: "根据您输入的词条随机生成" },
  gear: { lucideName: "Settings", name: "齿轮设置", desc: "根据您输入的词条随机生成" },
  folder: { lucideName: "Folder", name: "项目文件夹", desc: "根据您输入的词条随机生成" },
  file: { lucideName: "FileText", name: "文本文件", desc: "根据您输入的词条随机生成" },
  terminal: { lucideName: "Terminal", name: "控制台终端", desc: "根据您输入的词条随机生成" },
  code: { lucideName: "Code2", name: "编程代码", desc: "根据您输入的词条随机生成" },
  cpu: { lucideName: "Cpu", name: "高性能芯片", desc: "根据您输入的词条随机生成" },
  chip: { lucideName: "Cpu", name: "高性能芯片", desc: "根据您输入的词条随机生成" },
  heart: { lucideName: "Heart", name: "爱心喜欢", desc: "根据您输入的词条随机生成" },
  love: { lucideName: "Heart", name: "爱心喜欢", desc: "根据您输入的词条随机生成" },
  phone: { lucideName: "Phone", name: "电话呼叫", desc: "根据您输入的词条随机生成" },
  call: { lucideName: "Phone", name: "电话呼叫", desc: "根据您输入的词条随机生成" },
  video: { lucideName: "Video", name: "视频影像", desc: "根据您输入的词条随机生成" },
  camera: { lucideName: "Camera", name: "拍照相机", desc: "根据您输入的词条随机生成" },
  user: { lucideName: "Users", name: "个人中心", desc: "根据您输入的词条随机生成" },
  users: { lucideName: "Users", name: "用户群组", desc: "根据您输入的词条随机生成" },
  mail: { lucideName: "Mail", name: "电子邮件", desc: "根据您输入的词条随机生成" },
  email: { lucideName: "Mail", name: "电子邮件", desc: "根据您输入的词条随机生成" },
  play: { lucideName: "Play", name: "媒体播放", desc: "根据您输入的词条随机生成" },
  pause: { lucideName: "Pause", name: "媒体暂停", desc: "根据您输入的词条随机生成" },
  music: { lucideName: "Music", name: "动感音乐", desc: "根据您输入的词条随机生成" },
  song: { lucideName: "Music", name: "动感音乐", desc: "根据您输入的词条随机生成" },
  star: { lucideName: "Star", name: "璀璨星星", desc: "根据您输入的词条随机生成" },
  gift: { lucideName: "Gift", name: "节日礼包", desc: "根据您输入的词条随机生成" },
  present: { lucideName: "Gift", name: "节日礼包", desc: "根据您输入的词条随机生成" },
  bag: { lucideName: "ShoppingBag", name: "精品袋子", desc: "根据您输入的词条随机生成" },
  cart: { lucideName: "ShoppingCart", name: "超市购物车", desc: "根据您输入的词条随机生成" },
  shopping: { lucideName: "ShoppingCart", name: "超市购物车", desc: "根据您输入的词条随机生成" },
  dollar: { lucideName: "DollarSign", name: "美金符号", desc: "根据您输入的词条随机生成" },
  money: { lucideName: "Coins", name: "财富金币", desc: "根据您输入的词条随机生成" },
  coin: { lucideName: "Coins", name: "财富金币", desc: "根据您输入的词条随机生成" },
  wallet: { lucideName: "Wallet", name: "皮质钱包", desc: "根据您输入的词条随机生成" },
  card: { lucideName: "CreditCard", name: "信用卡", desc: "根据您输入的词条随机生成" },
  map: { lucideName: "Map", name: "旅行地图", desc: "根据您输入的词条随机生成" },
  pin: { lucideName: "MapPin", name: "地图坐标", desc: "根据您输入的词条随机生成" },
  gps: { lucideName: "Navigation", name: "GPS导航", desc: "根据您输入的词条随机生成" },
  plane: { lucideName: "Plane", name: "民航客机", desc: "根据您输入的词条随机生成" },
  flight: { lucideName: "Plane", name: "民航客机", desc: "根据您输入的词条随机生成" },
  train: { lucideName: "Train", name: "高速动车", desc: "根据您输入的词条随机生成" },
  car: { lucideName: "Car", name: "新能源车", desc: "根据您输入的词条随机生成" },
  home: { lucideName: "Home", name: "我的主页", desc: "根据您输入的词条随机生成" },
  house: { lucideName: "Home", name: "我的主页", desc: "根据您输入的词条随机生成" },
  bulb: { lucideName: "Lightbulb", name: "智能灯泡", desc: "根据您输入的词条随机生成" },
  light: { lucideName: "Lightbulb", name: "智能灯泡", desc: "根据您输入的词条随机生成" },
  tv: { lucideName: "Tv", name: "网络电视", desc: "根据您输入的词条随机生成" },
  bell: { lucideName: "Bell", name: "提醒风铃", desc: "根据您输入的词条随机生成" },
  notification: { lucideName: "Bell", name: "提醒风铃", desc: "根据您输入的词条随机生成" },
  activity: { lucideName: "Activity", name: "健康心率", desc: "根据您输入的词条随机生成" },
  pulse: { lucideName: "Activity", name: "健康心率", desc: "根据您输入的词条随机生成" },
  flame: { lucideName: "Flame", name: "炙热火焰", desc: "根据您输入的词条随机生成" },
  fire: { lucideName: "Flame", name: "炙热火焰", desc: "根据您输入的词条随机生成" },
  trophy: { lucideName: "Trophy", name: "金牌奖杯", desc: "根据您输入的词条随机生成" },
  winner: { lucideName: "Trophy", name: "金牌奖杯", desc: "根据您输入的词条随机生成" },
  cup: { lucideName: "Trophy", name: "金牌奖杯", desc: "根据您输入的词条随机生成" },
  brain: { lucideName: "Brain", name: "智脑神经网络", desc: "根据您输入的词条随机生成" },
  ai: { lucideName: "Bot", name: "AI对话助理", desc: "根据您输入的词条随机生成" },
  robot: { lucideName: "Bot", name: "AI对话助理", desc: "根据您输入的词条随机生成" },
  spark: { lucideName: "Sparkles", name: "魔法火花", desc: "根据您输入的词条随机生成" },
  magic: { lucideName: "Sparkles", name: "魔法火花", desc: "根据您输入的词条随机生成" },
  coffee: { lucideName: "Coffee", name: "热拿铁咖啡", desc: "根据您输入的词条随机生成" },
  pizza: { lucideName: "Pizza", name: "黄金披萨", desc: "根据您输入的词条随机生成" },
  cake: { lucideName: "Cake", name: "生日蛋糕", desc: "根据您输入的词条随机生成" },
  apple: { lucideName: "Apple", name: "红富士苹果", desc: "根据您输入的词条随机生成" },
  beer: { lucideName: "Beer", name: "清爽啤酒", desc: "根据您输入的词条随机生成" },
  mobile: { lucideName: "Smartphone", name: "智能手机", desc: "根据您输入的词条随机生成" },
  laptop: { lucideName: "Laptop", name: "笔记本电脑", desc: "根据您输入的词条随机生成" },
  computer: { lucideName: "Laptop", name: "工作站电脑", desc: "根据您输入的词条随机生成" },
  monitor: { lucideName: "Monitor", name: "高清显示器", desc: "根据您输入的词条随机生成" },
  headphone: { lucideName: "Headphones", name: "降噪耳机", desc: "根据您输入的词条随机生成" },
  headphones: { lucideName: "Headphones", name: "降噪耳机", desc: "根据您输入的词条随机生成" },
  speaker: { lucideName: "Speaker", name: "蓝牙音响", desc: "根据您输入的词条随机生成" },
  wifi: { lucideName: "Wifi", name: "Wi-Fi信号", desc: "根据您输入的词条随机生成" },
  bluetooth: { lucideName: "Bluetooth", name: "蓝牙配对", desc: "根据您输入的词条随机生成" },
  shield: { lucideName: "Shield", name: "安全盾牌", desc: "根据您输入的词条随机生成" },
  book: { lucideName: "BookOpen", name: "翻开的书本", desc: "根据您输入的词条随机生成" },
  leaf: { lucideName: "Leaf", name: "一片绿叶", desc: "根据您输入的词条随机生成" },
  sun: { lucideName: "Sun", name: "和煦烈阳", desc: "根据您输入的词条随机生成" },
  moon: { lucideName: "Moon", name: "弯弯明月", desc: "根据您输入的词条随机生成" },
  cloudy: { lucideName: "CloudRain", name: "乌云下雨", desc: "根据您输入的词条随机生成" },
  lightning: { lucideName: "CloudLightning", name: "雷电云朵", desc: "根据您输入的词条随机生成" },
  game: { lucideName: "Gamepad2", name: "电子手柄", desc: "根据您输入的词条随机生成" },
  dice: { lucideName: "Dices", name: "娱乐骰子", desc: "根据您输入的词条随机生成" },

  // Chinese matches
  "锁": { lucideName: "Lock", name: "安全锁", desc: "生成包含安全属性的图标" },
  "安全": { lucideName: "Shield", name: "防线盾牌", desc: "生成保护主题的图标" },
  "云": { lucideName: "Cloud", name: "云储存端", desc: "生成科技云概念的图标" },
  "数据库": { lucideName: "Database", name: "云端数据库", desc: "生成高负载存储的图标" },
  "设置": { lucideName: "Settings", name: "核心设置", desc: "生成关于控制和属性的图标" },
  "文件": { lucideName: "Folder", name: "共享文件夹", desc: "生成关于数据归档的图标" },
  "代码": { lucideName: "Code2", name: "核心程序段", desc: "生成关于技术开发的图标" },
  "编程": { lucideName: "Code2", name: "代码构建", desc: "生成关于程序员工作的图标" },
  "芯片": { lucideName: "Cpu", name: "AI神经计算元", desc: "生成关于高算力芯片的图标" },
  "爱心": { lucideName: "Heart", name: "社交红心", desc: "生成关于喜爱互动的图标" },
  "喜欢": { lucideName: "Heart", name: "点赞喜欢", desc: "生成关于粉丝推崇的图标" },
  "电话": { lucideName: "Phone", name: "实时通话", desc: "生成关于即时联系的图标" },
  "视频": { lucideName: "Video", name: "多人视频会议", desc: "生成关于多媒体对话的图标" },
  "相机": { lucideName: "Camera", name: "光学相机", desc: "生成关于摄影留念的图标" },
  "用户": { lucideName: "Users", name: "账户与群组", desc: "生成关于社交关系的图标" },
  "人": { lucideName: "Users", name: "账户关系", desc: "生成关于团队合作的图标" },
  "邮件": { lucideName: "Mail", name: "已收发信件", desc: "生成关于高效收信的图标" },
  "播放": { lucideName: "Play", name: "影音播放键", desc: "生成关于启动视听的图标" },
  "音乐": { lucideName: "Music", name: "高品质乐符", desc: "生成关于艺术灵动的图标" },
  "星星": { lucideName: "Star", name: "金牌勋章", desc: "生成关于荣誉打分的图标" },
  "礼物": { lucideName: "Gift", name: "满减大礼盒", desc: "生成关于商业福利的图标" },
  "购物": { lucideName: "ShoppingCart", name: "满载购物车", desc: "生成关于电商选购的图标" },
  "钱包": { lucideName: "Wallet", name: "数字钱包", desc: "生成关于财务结余的图标" },
  "卡": { lucideName: "CreditCard", name: "银联信用卡", desc: "生成关于绑定消费的图标" },
  "地图": { lucideName: "Map", name: "离线全景图", desc: "生成关于出差旅游的图标" },
  "定位": { lucideName: "MapPin", name: "精准基站坐标", desc: "生成关于地理标记的图标" },
  "导航": { lucideName: "Navigation", name: "三维路径引导", desc: "生成关于实时导航的图标" },
  "飞机": { lucideName: "Plane", name: "国际航班", desc: "生成关于跨国飞行的图标" },
  "火车": { lucideName: "Train", name: "和谐号列车", desc: "生成关于中短途客运的图标" },
  "车": { lucideName: "Car", name: "智能轿跑", desc: "生成关于租车出行的图标" },
  "家": { lucideName: "Home", name: "智能主页", desc: "生成关于归家港湾的图标" },
  "灯": { lucideName: "Lightbulb", name: "智能LED灯", desc: "生成关于启迪灵感的图标" },
  "电视": { lucideName: "Tv", name: "无边框智慧屏", desc: "生成关于客厅娱乐的图标" },
  "提醒": { lucideName: "Bell", name: "高分贝警报", desc: "生成关于系统通知的图标" },
  "心率": { lucideName: "Activity", name: "血氧心脉图", desc: "生成关于生理检测的图标" },
  "火": { lucideName: "Flame", name: "社区热度榜", desc: "生成关于今日最火的图标" },
  "奖杯": { lucideName: "Trophy", name: "超级总冠军", desc: "生成关于竞技桂冠的图标" },
  "大脑": { lucideName: "Brain", name: "AI云端神经网络", desc: "生成关于自主思考的图标" },
  "机器人": { lucideName: "Bot", name: "客服机器人", desc: "生成关于人机交互的图标" },
  "魔法": { lucideName: "Sparkles", name: "AI润色特效", desc: "生成关于智能增强的图标" },
  "咖啡": { lucideName: "Coffee", name: "美式纯黑咖啡", desc: "生成关于打工人提神的图标" },
  "披萨": { lucideName: "Pizza", name: "意式香肠披萨", desc: "生成关于快餐零食的图标" },
  "蛋糕": { lucideName: "Cake", name: "乳酪小蛋糕", desc: "生成关于庆祝礼仪的图标" },
  "苹果": { lucideName: "Apple", name: "维C绿苹果", desc: "生成关于健康饮食的图标" },
  "手机": { lucideName: "Smartphone", name: "5G折叠手机", desc: "生成关于无线互联的图标" },
  "电脑": { lucideName: "Laptop", name: "视网膜笔记本", desc: "生成关于极客生产力的图标" },
  "显示器": { lucideName: "Monitor", name: "曲面带鱼屏", desc: "生成关于超宽画幅的图标" },
  "耳机": { lucideName: "Headphones", name: "Hi-Fi发烧友机", desc: "生成关于降噪沉浸的图标" },
  "音箱": { lucideName: "Speaker", name: "声学低音炮", desc: "生成关于外放音质的图标" },
  "网络": { lucideName: "Wifi", name: "无线局域网", desc: "生成关于信号传输的图标" },
  "书": { lucideName: "BookOpen", name: "百科全书", desc: "生成关于博闻强记的图标" },
  "叶子": { lucideName: "Leaf", name: "常青灌木叶", desc: "生成关于生命与生态的图标" },
  "太阳": { lucideName: "Sun", name: "骄阳似火", desc: "生成关于白天采光的图标" },
  "月亮": { lucideName: "Moon", name: "寂静暗夜月", desc: "生成关于护眼黑夜的图标" },
  "雨": { lucideName: "CloudRain", name: "梅雨季节", desc: "生成关于多云降水的图标" },
  "雷": { lucideName: "CloudLightning", name: "蓝色雷暴", desc: "生成关于极端气候的图标" },
  "游戏": { lucideName: "Gamepad2", name: "掌上游戏机", desc: "生成关于二次元娱乐的图标" },
  "骰子": { lucideName: "Dices", name: "桌游筹码", desc: "生成关于随机运气的图标" },
};
