/** 拓展主题：6 大类 × 5 子分类 × 10 图标 */
export const expandedThemesData = [
  {
    id: "ani-pets",
    name: "萌宠日常",
    englishName: "Pets & Companions",
    description: "猫狗兔等家庭萌宠互动图标",
    icon: "Cat",
    icons: [
      { id: "apet-1", name: "家猫", lucideName: "Cat", desc: "慵懒家猫陪伴", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "apet-2", name: "忠犬", lucideName: "Dog", desc: "忠诚守护伙伴", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "apet-3", name: "小兔", lucideName: "Rabbit", desc: "软萌跳跃宠物", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "apet-4", name: "金鱼", lucideName: "Fish", desc: "观赏鱼缸精灵", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "apet-5", name: "鸟笼", lucideName: "Bird", desc: "鸣禽与鹦鹉", defaultGradient: ["#10b981", "#047857"] },
      { id: "apet-6", name: "仓鼠", lucideName: "Squirrel", desc: "小巧活泼宠物", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "apet-7", name: "乌龟", lucideName: "Turtle", desc: "慢节奏长寿宠", defaultGradient: ["#10b981", "#047857"] },
      { id: "apet-8", name: "蜗牛", lucideName: "Snail", desc: "慢生活治愈系", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "apet-9", name: "爪印", lucideName: "PawPrint", desc: "宠物足迹留念", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "apet-10", name: "宠物碗", lucideName: "Utensils", desc: "定时投喂提醒", defaultGradient: ["#64748b", "#334155"] },
    ],
  },
  {
    id: "ani-wild",
    name: "野生动物",
    englishName: "Wild Animals",
    description: "森林草原野生动物图标",
    icon: "Trees",
    icons: [
      { id: "awld-1", name: "松鼠", lucideName: "Squirrel", desc: "林间敏捷跳跃", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "awld-2", name: "野兔", lucideName: "Rabbit", desc: "草原奔跑生灵", defaultGradient: ["#10b981", "#047857"] },
      { id: "awld-3", name: "飞鸟", lucideName: "Bird", desc: "天空自由翱翔", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "awld-4", name: "游鱼", lucideName: "Fish", desc: "溪流野生鱼群", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "awld-5", name: "昆虫", lucideName: "Bug", desc: "微观生态链", defaultGradient: ["#84cc16", "#65a30d"] },
      { id: "awld-6", name: "龟甲", lucideName: "Turtle", desc: "湿地缓慢爬行", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "awld-7", name: "密林", lucideName: "Trees", desc: "野生动物栖息地", defaultGradient: ["#10b981", "#047857"] },
      { id: "awld-8", name: "山峰", lucideName: "Mountain", desc: "高山猛兽领地", defaultGradient: ["#64748b", "#334155"] },
      { id: "awld-9", name: "足迹", lucideName: "Footprints", desc: "追踪动物痕迹", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "awld-10", name: "望远镜", lucideName: "Binoculars", desc: "远距生态观察", defaultGradient: ["#6366f1", "#4f46e5"] },
    ],
  },
  {
    id: "ani-sea",
    name: "海洋生物",
    englishName: "Marine Life",
    description: "深海浅海海洋生物图标",
    icon: "Fish",
    icons: [
      { id: "asea-1", name: "热带鱼", lucideName: "Fish", desc: "珊瑚礁观赏鱼", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "asea-2", name: "海浪", lucideName: "Waves", desc: "潮汐涌动浪花", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "asea-3", name: "船锚", lucideName: "Anchor", desc: "港口停泊定位", defaultGradient: ["#64748b", "#334155"] },
      { id: "asea-4", name: "帆船", lucideName: "Sailboat", desc: "近海扬帆航行", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "asea-5", name: "远洋轮", lucideName: "Ship", desc: "深海科考航行", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "asea-6", name: "贝壳", lucideName: "Shell", desc: "海滩拾贝纪念", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "asea-7", name: "水滴", lucideName: "Droplet", desc: "海水纯净度", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "asea-8", name: "地球水域", lucideName: "Globe", desc: "全球海洋覆盖", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "asea-9", name: "潜水", lucideName: "Glasses", desc: "水下潜游装备", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "asea-10", name: "指南针", lucideName: "Compass", desc: "海上导航定位", defaultGradient: ["#f59e0b", "#d97706"] },
    ],
  },
  {
    id: "ani-bird",
    name: "飞禽鸟类",
    englishName: "Birds & Aviary",
    description: "候鸟鸣禽与观鸟图标",
    icon: "Bird",
    icons: [
      { id: "abrd-1", name: "麻雀", lucideName: "Bird", desc: "城市常见飞鸟", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "abrd-2", name: "羽翼", lucideName: "Feather", desc: "轻盈飞翔翅膀", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "abrd-3", name: "日出观鸟", lucideName: "Sunrise", desc: "清晨林间观鸟", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "abrd-4", name: "月亮夜栖", lucideName: "Moon", desc: "夜行鸟类栖息", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "abrd-5", name: "树梢", lucideName: "TreePine", desc: "枝头筑巢地点", defaultGradient: ["#10b981", "#047857"] },
      { id: "abrd-6", name: "森林", lucideName: "Trees", desc: "鸟类天然家园", defaultGradient: ["#84cc16", "#65a30d"] },
      { id: "abrd-7", name: "双筒镜", lucideName: "Binoculars", desc: "远距离观鸟", defaultGradient: ["#64748b", "#334155"] },
      { id: "abrd-8", name: "相机抓拍", lucideName: "Camera", desc: "记录飞鸟瞬间", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "abrd-9", name: "风向标", lucideName: "Wind", desc: "气流飞行辅助", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "abrd-10", name: "地图迁徙", lucideName: "Map", desc: "候鸟迁徙路线", defaultGradient: ["#10b981", "#047857"] },
    ],
  },
  {
    id: "ani-bug",
    name: "昆虫爬虫",
    englishName: "Insects & Reptiles",
    description: "昆虫与小型爬行动物图标",
    icon: "Bug",
    icons: [
      { id: "abug-1", name: "甲虫", lucideName: "Bug", desc: "微观昆虫世界", defaultGradient: ["#84cc16", "#65a30d"] },
      { id: "abug-2", name: "蜗牛慢爬", lucideName: "Snail", desc: "湿润慢行者", defaultGradient: ["#10b981", "#047857"] },
      { id: "abug-3", name: "乌龟爬行", lucideName: "Turtle", desc: "甲壳爬行动物", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "abug-4", name: "叶片", lucideName: "Leaf", desc: "昆虫栖息叶片", defaultGradient: ["#10b981", "#047857"] },
      { id: "abug-5", name: "花朵", lucideName: "Flower", desc: "授粉昆虫乐园", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "abug-6", name: "放大镜", lucideName: "Search", desc: "微观昆虫观察", defaultGradient: ["#64748b", "#334155"] },
      { id: "abug-7", name: "显微镜", lucideName: "Microscope", desc: "实验室标本", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "abug-8", name: "试管", lucideName: "FlaskConical", desc: "昆虫样本保存", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "abug-9", name: "记录本", lucideName: "Notebook", desc: "田野调查笔记", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "abug-10", name: "标本夹", lucideName: "ClipboardList", desc: "分类归档记录", defaultGradient: ["#64748b", "#334155"] },
    ],
  },
  {
    id: "bld-landmark",
    name: "地标建筑",
    englishName: "Landmarks",
    description: "著名建筑与城市地标图标",
    icon: "Landmark",
    icons: [
      { id: "blmk-1", name: "地标塔", lucideName: "Landmark", desc: "城市象征建筑", defaultGradient: ["#64748b", "#334155"] },
      { id: "blmk-2", name: "古典城堡", lucideName: "Castle", desc: "历史古堡遗迹", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "blmk-3", name: "摩天楼", lucideName: "Building2", desc: "高层商务大厦", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "blmk-4", name: "办公楼", lucideName: "Building", desc: "企业总部大楼", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "blmk-5", name: "工厂烟囱", lucideName: "Factory", desc: "工业制造园区", defaultGradient: ["#64748b", "#334155"] },
      { id: "blmk-6", name: "仓储物流", lucideName: "Warehouse", desc: "大型货物仓库", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "blmk-7", name: "银行大厦", lucideName: "Landmark", desc: "金融核心建筑", defaultGradient: ["#10b981", "#047857"] },
      { id: "blmk-8", name: "学校校舍", lucideName: "School", desc: "校园教学楼群", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "blmk-9", name: "医院大楼", lucideName: "Hospital", desc: "医疗救治中心", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "blmk-10", name: "宗教殿堂", lucideName: "Church", desc: "教堂庙宇建筑", defaultGradient: ["#8b5cf6", "#6d28d9"] },
    ],
  },
  {
    id: "bld-construct",
    name: "施工建设",
    englishName: "Construction",
    description: "工地施工与建造过程图标",
    icon: "Hammer",
    icons: [
      { id: "bcon-1", name: "施工锤", lucideName: "Hammer", desc: "敲击加固作业", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "bcon-2", name: "安全帽", lucideName: "HardHat", desc: "工地安全防护", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "bcon-3", name: "路障锥", lucideName: "TrafficCone", desc: "施工区域警示", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "bcon-4", name: "工程建造", lucideName: "Construction", desc: "大型基建项目", defaultGradient: ["#64748b", "#334155"] },
      { id: "bcon-5", name: "扳手工具", lucideName: "Wrench", desc: "机械安装调试", defaultGradient: ["#64748b", "#334155"] },
      { id: "bcon-6", name: "电钻", lucideName: "Drill", desc: "墙面打孔作业", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "bcon-7", name: "斧头", lucideName: "Axe", desc: "木料切割加工", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "bcon-8", name: "铁镐", lucideName: "Pickaxe", desc: "地基开挖工具", defaultGradient: ["#64748b", "#334155"] },
      { id: "bcon-9", name: "铁砧", lucideName: "Anvil", desc: "金属锻造平台", defaultGradient: ["#1e293b", "#0f172a"] },
      { id: "bcon-10", name: "围栏", lucideName: "Fence", desc: "工地边界围挡", defaultGradient: ["#10b981", "#047857"] },
    ],
  },
  {
    id: "bld-interior",
    name: "室内空间",
    englishName: "Interior Design",
    description: "家装室内与软装图标",
    icon: "Sofa",
    icons: [
      { id: "bint-1", name: "沙发", lucideName: "Sofa", desc: "客厅休闲座椅", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "bint-2", name: "床铺", lucideName: "Bed", desc: "卧室休息空间", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "bint-3", name: "台灯", lucideName: "Lamp", desc: "局部氛围照明", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "bint-4", name: "落地灯", lucideName: "LampFloor", desc: "角落柔和灯光", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "bint-5", name: "书架", lucideName: "BookOpen", desc: "墙面收纳展示", defaultGradient: ["#64748b", "#334155"] },
      { id: "bint-6", name: "窗帘", lucideName: "Blinds", desc: "遮光隐私调节", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "bint-7", name: "地毯", lucideName: "RectangleHorizontal", desc: "地面软装铺设", defaultGradient: ["#f43f5e", "#be123c"] },
      { id: "bint-8", name: "花瓶", lucideName: "Flower", desc: "桌面花艺装饰", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "bint-9", name: "挂画", lucideName: "Frame", desc: "墙面艺术点缀", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "bint-10", name: "浴室", lucideName: "Bath", desc: "卫浴清洁空间", defaultGradient: ["#38bdf8", "#0284c7"] },
    ],
  },
  {
    id: "bld-urban",
    name: "城市规划",
    englishName: "Urban Planning",
    description: "市政交通与城市布局图标",
    icon: "Map",
    icons: [
      { id: "burb-1", name: "城市地图", lucideName: "Map", desc: "城区规划蓝图", defaultGradient: ["#10b981", "#047857"] },
      { id: "burb-2", name: "路标", lucideName: "Signpost", desc: "道路方向指引", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "burb-3", name: "精准定位", lucideName: "MapPinned", desc: "地块坐标标记", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "burb-4", name: "公交线路", lucideName: "Bus", desc: "公共交通网络", defaultGradient: ["#10b981", "#047857"] },
      { id: "burb-5", name: "地铁轨道", lucideName: "Train", desc: "地下轨道交通", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "burb-6", name: "交通灯", lucideName: "TrafficCone", desc: "路口秩序管理", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "burb-7", name: "加油站", lucideName: "Fuel", desc: "能源补给站点", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "burb-8", name: "停车场", lucideName: "Car", desc: "车辆停放区域", defaultGradient: ["#64748b", "#334155"] },
      { id: "burb-9", name: "网格布局", lucideName: "Grid3x3", desc: "街区网格规划", defaultGradient: ["#64748b", "#334155"] },
      { id: "burb-10", name: "分区图层", lucideName: "Layers", desc: "功能分区叠加", defaultGradient: ["#8b5cf6", "#6d28d9"] },
    ],
  },
  {
    id: "bld-infra",
    name: "基础设施",
    englishName: "Infrastructure",
    description: "水电管网与公共设施图标",
    icon: "Plug",
    icons: [
      { id: "binf-1", name: "电力插座", lucideName: "Plug", desc: "供电接口节点", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "binf-2", name: "水管阀门", lucideName: "Droplets", desc: "供水管网控制", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "binf-3", name: "路由器", lucideName: "Router", desc: "通信网络枢纽", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "binf-4", name: "服务器", lucideName: "Server", desc: "数据中心机房", defaultGradient: ["#64748b", "#334155"] },
      { id: "binf-5", name: "集装箱", lucideName: "Container", desc: "货运周转单元", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "binf-6", name: "叉车", lucideName: "Forklift", desc: "仓储搬运设备", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "binf-7", name: "货运卡车", lucideName: "Truck", desc: "公路货物运输", defaultGradient: ["#64748b", "#334155"] },
      { id: "binf-8", name: "消防栓", lucideName: "FireExtinguisher", desc: "消防安全设施", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "binf-9", name: "警报器", lucideName: "Siren", desc: "公共预警系统", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "binf-10", name: "路灯", lucideName: "Lightbulb", desc: "夜间道路照明", defaultGradient: ["#f59e0b", "#d97706"] },
    ],
  },
  {
    id: "fsh-cloth",
    name: "服饰穿搭",
    englishName: "Clothing",
    description: "日常穿搭与服装品类图标",
    icon: "Shirt",
    icons: [
      { id: "fclo-1", name: "T恤衫", lucideName: "Shirt", desc: "休闲上衣搭配", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "fclo-2", name: "礼服裙", lucideName: "Shirt", desc: "正式场合着装", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "fclo-3", name: "围巾", lucideName: "Ribbon", desc: "秋冬保暖配饰", defaultGradient: ["#f43f5e", "#be123c"] },
      { id: "fclo-4", name: "皇冠", lucideName: "Crown", desc: "高端奢华系列", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "fclo-5", name: "徽章", lucideName: "Badge", desc: "品牌标识刺绣", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "fclo-6", name: "尺码尺", lucideName: "Ruler", desc: "合身尺寸测量", defaultGradient: ["#64748b", "#334155"] },
      { id: "fclo-7", name: "剪刀裁剪", lucideName: "Scissors", desc: "定制剪裁工艺", defaultGradient: ["#64748b", "#334155"] },
      { id: "fclo-8", name: "针线", lucideName: "Pen", desc: "手工缝纫细节", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "fclo-9", name: "衣架", lucideName: "Shirt", desc: "衣柜陈列收纳", defaultGradient: ["#64748b", "#334155"] },
      { id: "fclo-10", name: "购物袋", lucideName: "ShoppingBag", desc: "新品购买带走", defaultGradient: ["#ec4899", "#be185d"] },
    ],
  },
  {
    id: "fsh-access",
    name: "珠宝配饰",
    englishName: "Accessories",
    description: "首饰手表与精致配饰图标",
    icon: "Gem",
    icons: [
      { id: "facc-1", name: "宝石", lucideName: "Gem", desc: "璀璨钻石珠宝", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "facc-2", name: "手表", lucideName: "Watch", desc: "精致腕间时计", defaultGradient: ["#64748b", "#334155"] },
      { id: "facc-3", name: "眼镜", lucideName: "Glasses", desc: "时尚镜框搭配", defaultGradient: ["#64748b", "#334155"] },
      { id: "facc-4", name: "丝带", lucideName: "Ribbon", desc: "礼盒装饰丝带", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "facc-5", name: "奖章", lucideName: "Medal", desc: "荣誉勋章配饰", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "facc-6", name: "星星", lucideName: "Star", desc: "闪耀点缀元素", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "facc-7", name: "皇冠头饰", lucideName: "Crown", desc: "华贵头冠饰品", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "facc-8", name: "钥匙扣", lucideName: "Key", desc: "随身小物挂件", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "facc-9", name: "礼盒", lucideName: "Gift", desc: "首饰精美包装", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "facc-10", name: "标签", lucideName: "Tag", desc: "品牌吊牌价格", defaultGradient: ["#f97316", "#c2410c"] },
    ],
  },
  {
    id: "fsh-beauty",
    name: "美容护肤",
    englishName: "Beauty & Skincare",
    description: "护肤彩妆与美容护理图标",
    icon: "Sparkles",
    icons: [
      { id: "fbea-1", name: "闪耀", lucideName: "Sparkles", desc: "肌肤光泽焕亮", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "fbea-2", name: "化妆刷", lucideName: "Brush", desc: "彩妆上妆工具", defaultGradient: ["#f43f5e", "#be123c"] },
      { id: "fbea-3", name: "镜子", lucideName: "Scan", desc: "妆容检查镜", defaultGradient: ["#64748b", "#334155"] },
      { id: "fbea-4", name: "水滴精华", lucideName: "Droplet", desc: "保湿精华液", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "fbea-5", name: "花瓣面膜", lucideName: "Flower", desc: "植物护肤面膜", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "fbea-6", name: "香水", lucideName: "Sprout", desc: "芬芳香氛喷雾", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "fbea-7", name: "指甲", lucideName: "Hand", desc: "美甲护理服务", defaultGradient: ["#f43f5e", "#be123c"] },
      { id: "fbea-8", name: "吹风机", lucideName: "Wind", desc: "发型吹干造型", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "fbea-9", name: "梳子", lucideName: "AlignJustify", desc: "梳理顺滑发丝", defaultGradient: ["#64748b", "#334155"] },
      { id: "fbea-10", name: "浴缸", lucideName: "Bath", desc: "SPA放松护理", defaultGradient: ["#38bdf8", "#0284c7"] },
    ],
  },
  {
    id: "fsh-shoes",
    name: "鞋靴箱包",
    englishName: "Shoes & Bags",
    description: "鞋履箱包与出行搭配图标",
    icon: "Backpack",
    icons: [
      { id: "fsho-1", name: "背包", lucideName: "Backpack", desc: "日常通勤背包", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "fsho-2", name: "行李箱", lucideName: "Luggage", desc: "旅行拉杆箱包", defaultGradient: ["#64748b", "#334155"] },
      { id: "fsho-3", name: "购物袋", lucideName: "ShoppingBag", desc: "逛街购物手提", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "fsho-4", name: "公文包", lucideName: "Briefcase", desc: "商务皮质手袋", defaultGradient: ["#64748b", "#334155"] },
      { id: "fsho-5", name: "包裹", lucideName: "Package", desc: "快递鞋盒包装", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "fsho-6", name: "鞋印", lucideName: "Footprints", desc: "步行足迹记录", defaultGradient: ["#10b981", "#047857"] },
      { id: "fsho-7", name: "尺码", lucideName: "Ruler", desc: "鞋码精准测量", defaultGradient: ["#64748b", "#334155"] },
      { id: "fsho-8", name: "标签价", lucideName: "Tag", desc: "新品吊牌价格", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "fsho-9", name: "星星好评", lucideName: "Star", desc: "买家五星评价", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "fsho-10", name: "礼物盒", lucideName: "Gift", desc: "节日赠礼包装", defaultGradient: ["#ef4444", "#b91c1c"] },
    ],
  },
  {
    id: "fsh-trend",
    name: "潮流街拍",
    englishName: "Street Fashion",
    description: "街拍潮流与时尚活动图标",
    icon: "Camera",
    icons: [
      { id: "ftrd-1", name: "街拍相机", lucideName: "Camera", desc: "捕捉街头造型", defaultGradient: ["#64748b", "#334155"] },
      { id: "ftrd-2", name: "闪光灯", lucideName: "Flashlight", desc: "夜间补光拍摄", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ftrd-3", name: "视频街拍", lucideName: "Video", desc: "动态穿搭记录", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "ftrd-4", name: "分享潮流", lucideName: "Share2", desc: "社交平台发布", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ftrd-5", name: "点赞热度", lucideName: "Heart", desc: "穿搭受欢迎度", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ftrd-6", name: "话题标签", lucideName: "Hash", desc: "潮流话题标记", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "ftrd-7", name: "麦克风", lucideName: "Mic", desc: "时尚采访录音", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "ftrd-8", name: "舞台走秀", lucideName: "Zap", desc: "秀场灯光焦点", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ftrd-9", name: "奖杯", lucideName: "Trophy", desc: "设计大赛获奖", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "ftrd-10", name: "日历活动", lucideName: "Calendar", desc: "时装周日程", defaultGradient: ["#3b82f6", "#1d4ed8"] },
    ],
  },
  {
    id: "frm-crop",
    name: "农作物",
    englishName: "Crops",
    description: "粮食果蔬与经济作物图标",
    icon: "Wheat",
    icons: [
      { id: "fcrop-1", name: "小麦", lucideName: "Wheat", desc: "金黄麦穗丰收", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "fcrop-2", name: "苹果", lucideName: "Apple", desc: "果园红富士", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "fcrop-3", name: "樱桃", lucideName: "Cherry", desc: "初夏浆果采摘", defaultGradient: ["#f43f5e", "#be123c"] },
      { id: "fcrop-4", name: "葡萄", lucideName: "Grape", desc: "藤蔓挂果成熟", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "fcrop-5", name: "柑橘", lucideName: "Citrus", desc: "柑橘类水果", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "fcrop-6", name: "胡萝卜", lucideName: "Carrot", desc: "根茎蔬菜种植", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "fcrop-7", name: "沙拉菜", lucideName: "Salad", desc: "绿叶蔬菜组合", defaultGradient: ["#10b981", "#047857"] },
      { id: "fcrop-8", name: "饼干谷", lucideName: "Cookie", desc: "谷物烘焙原料", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "fcrop-9", name: "糖果", lucideName: "Candy", desc: "甜蜜农产品加工", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "fcrop-10", name: "种子", lucideName: "Sprout", desc: "播种育苗起点", defaultGradient: ["#84cc16", "#65a30d"] },
    ],
  },
  {
    id: "frm-garden",
    name: "园艺花卉",
    englishName: "Gardening",
    description: "庭院园艺与花卉培育图标",
    icon: "Flower",
    icons: [
      { id: "fgar-1", name: "盛开", lucideName: "Flower", desc: "庭院鲜花绽放", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "fgar-2", name: "嫩苗", lucideName: "Sprout", desc: "新芽破土生长", defaultGradient: ["#84cc16", "#65a30d"] },
      { id: "fgar-3", name: "绿叶", lucideName: "Leaf", desc: "健康叶片繁茂", defaultGradient: ["#10b981", "#047857"] },
      { id: "fgar-4", name: "松树", lucideName: "TreePine", desc: "常青景观树木", defaultGradient: ["#10b981", "#047857"] },
      { id: "fgar-5", name: "阔叶树", lucideName: "TreeDeciduous", desc: "四季变换乔木", defaultGradient: ["#84cc16", "#65a30d"] },
      { id: "fgar-6", name: "浇水", lucideName: "Droplets", desc: "定时灌溉养护", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "fgar-7", name: "阳光", lucideName: "Sun", desc: "光合作用能量", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "fgar-8", name: "铲子", lucideName: "Shovel", desc: "松土翻耕工具", defaultGradient: ["#64748b", "#334155"] },
      { id: "fgar-9", name: "剪刀", lucideName: "Scissors", desc: "修剪枝叶造型", defaultGradient: ["#64748b", "#334155"] },
      { id: "fgar-10", name: "花盆", lucideName: "Sprout", desc: "盆栽绿植摆放", defaultGradient: ["#10b981", "#047857"] },
    ],
  },
  {
    id: "frm-tool",
    name: "农机工具",
    englishName: "Farm Tools",
    description: "农业生产机械与农具图标",
    icon: "Tractor",
    icons: [
      { id: "ftool-1", name: "拖拉机", lucideName: "Tractor", desc: "田间牵引动力", defaultGradient: ["#10b981", "#047857"] },
      { id: "ftool-2", name: "铁锹", lucideName: "Shovel", desc: "翻土挖坑农具", defaultGradient: ["#64748b", "#334155"] },
      { id: "ftool-3", name: "斧头", lucideName: "Axe", desc: "砍伐清理林木", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ftool-4", name: "铁镐", lucideName: "Pickaxe", desc: "坚硬土壤开垦", defaultGradient: ["#64748b", "#334155"] },
      { id: "ftool-5", name: "锤子", lucideName: "Hammer", desc: "搭建农舍围栏", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ftool-6", name: "扳手", lucideName: "Wrench", desc: "机械维修保养", defaultGradient: ["#64748b", "#334155"] },
      { id: "ftool-7", name: "电钻", lucideName: "Drill", desc: "设备安装打孔", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ftool-8", name: "货车", lucideName: "Truck", desc: "农产品运输", defaultGradient: ["#64748b", "#334155"] },
      { id: "ftool-9", name: "叉车", lucideName: "Forklift", desc: "粮仓装卸搬运", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "ftool-10", name: "围栏", lucideName: "Fence", desc: "牧场边界划分", defaultGradient: ["#10b981", "#047857"] },
    ],
  },
  {
    id: "frm-livestock",
    name: "畜牧养殖",
    englishName: "Livestock",
    description: "家禽牲畜与养殖管理图标",
    icon: "Egg",
    icons: [
      { id: "flive-1", name: "鸡蛋", lucideName: "Egg", desc: "家禽产蛋收获", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "flive-2", name: "鸡腿", lucideName: "Drumstick", desc: "禽类肉制品", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "flive-3", name: "牛奶", lucideName: "Milk", desc: "牧场鲜奶采集", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "flive-4", name: "狗看护", lucideName: "Dog", desc: "牧场巡逻守护", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "flive-5", name: "猫捕鼠", lucideName: "Cat", desc: "粮仓防鼠卫士", defaultGradient: ["#64748b", "#334155"] },
      { id: "flive-6", name: "兔子", lucideName: "Rabbit", desc: "小型牲畜养殖", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "flive-7", name: "鱼池", lucideName: "Fish", desc: "水产池塘养殖", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "flive-8", name: "鸟禽", lucideName: "Bird", desc: "散养家禽群体", defaultGradient: ["#10b981", "#047857"] },
      { id: "flive-9", name: "饲料", lucideName: "Wheat", desc: "谷物饲料配比", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "flive-10", name: "储罐", lucideName: "Cylinder", desc: "饲料储存容器", defaultGradient: ["#64748b", "#334155"] },
    ],
  },
  {
    id: "frm-rural",
    name: "田园风光",
    englishName: "Rural Scenery",
    description: "乡村自然与田园生活图标",
    icon: "Mountain",
    icons: [
      { id: "frur-1", name: "远山", lucideName: "Mountain", desc: "层峦叠嶂远景", defaultGradient: ["#64748b", "#334155"] },
      { id: "frur-2", name: "森林", lucideName: "Trees", desc: "乡间茂密树林", defaultGradient: ["#10b981", "#047857"] },
      { id: "frur-3", name: "日出", lucideName: "Sunrise", desc: "清晨田间晨曦", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "frur-4", name: "彩虹", lucideName: "Rainbow", desc: "雨后天空奇观", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "frur-5", name: "云朵", lucideName: "Cloud", desc: "田园天空云彩", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "frur-6", name: "微风", lucideName: "Wind", desc: "麦浪随风摇曳", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "frur-7", name: "小溪", lucideName: "Waves", desc: "灌溉水渠溪流", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "frur-8", name: "帐篷", lucideName: "Tent", desc: "乡间露营体验", defaultGradient: ["#10b981", "#047857"] },
      { id: "frur-9", name: "篝火", lucideName: "Flame", desc: "夜晚篝火晚会", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "frur-10", name: "小径", lucideName: "Route", desc: "田间漫步小路", defaultGradient: ["#84cc16", "#65a30d"] },
    ],
  },
  {
    id: "law-doc",
    name: "法律文书",
    englishName: "Legal Documents",
    description: "合同诉状与公证文书图标",
    icon: "ScrollText",
    icons: [
      { id: "ldoc-1", name: "卷宗", lucideName: "ScrollText", desc: "案件卷宗归档", defaultGradient: ["#64748b", "#334155"] },
      { id: "ldoc-2", name: "合同", lucideName: "FileText", desc: "双方协议签署", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ldoc-3", name: "印章", lucideName: "Stamp", desc: "官方盖章认证", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ldoc-4", name: "签名", lucideName: "Pen", desc: "手写签字确认", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "ldoc-5", name: "书签", lucideName: "BookMarked", desc: "法条重点标记", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ldoc-6", name: "档案夹", lucideName: "Folder", desc: "分类存放文书", defaultGradient: ["#64748b", "#334155"] },
      { id: "ldoc-7", name: "剪贴", lucideName: "Clipboard", desc: "庭审记录板", defaultGradient: ["#64748b", "#334155"] },
      { id: "ldoc-8", name: "清单", lucideName: "ClipboardList", desc: "证据材料列表", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ldoc-9", name: "加密", lucideName: "FileKey", desc: "涉密文件保护", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "ldoc-10", name: "公证", lucideName: "BadgeCheck", desc: "法律效力认证", defaultGradient: ["#10b981", "#047857"] },
    ],
  },
  {
    id: "law-gov",
    name: "政府机构",
    englishName: "Government",
    description: "政务办公与公共服务图标",
    icon: "Landmark",
    icons: [
      { id: "lgov-1", name: "政府大楼", lucideName: "Landmark", desc: "行政服务中心", defaultGradient: ["#64748b", "#334155"] },
      { id: "lgov-2", name: "身份证", lucideName: "IdCard", desc: "公民身份凭证", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "lgov-3", name: "徽章", lucideName: "Badge", desc: "公务人员标识", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "lgov-4", name: "公告", lucideName: "Megaphone", desc: "政策信息发布", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "lgov-5", name: "报纸", lucideName: "Newspaper", desc: "政务公开通报", defaultGradient: ["#64748b", "#334155"] },
      { id: "lgov-6", name: "邮箱", lucideName: "Mail", desc: "政务信件收发", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "lgov-7", name: "电话", lucideName: "Phone", desc: "市民服务热线", defaultGradient: ["#10b981", "#047857"] },
      { id: "lgov-8", name: "日历", lucideName: "Calendar", desc: "政务工作日程", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "lgov-9", name: "用户", lucideName: "Users", desc: "公务员团队", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "lgov-10", name: "握手", lucideName: "Handshake", desc: "政企合作签约", defaultGradient: ["#10b981", "#047857"] },
    ],
  },
  {
    id: "law-justice",
    name: "公共秩序",
    englishName: "Public Order",
    description: "执法安保与秩序维护图标",
    icon: "Scale",
    icons: [
      { id: "ljust-1", name: "天平", lucideName: "Scale", desc: "公正司法象征", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ljust-2", name: "法槌", lucideName: "Gavel", desc: "庭审宣判敲击", defaultGradient: ["#64748b", "#334155"] },
      { id: "ljust-3", name: "盾牌", lucideName: "Shield", desc: "执法力量保护", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ljust-4", name: "警铃", lucideName: "Siren", desc: "紧急事件警报", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ljust-5", name: "救护车", lucideName: "Ambulance", desc: "医疗急救响应", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ljust-6", name: "灭火器", lucideName: "FireExtinguisher", desc: "消防安全处置", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ljust-7", name: "监控", lucideName: "Cctv", desc: "公共区域监控", defaultGradient: ["#64748b", "#334155"] },
      { id: "ljust-8", name: "指纹", lucideName: "Fingerprint", desc: "身份生物识别", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "ljust-9", name: "钥匙", lucideName: "Key", desc: "门禁权限管理", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ljust-10", name: "锁", lucideName: "Lock", desc: "重要场所封锁", defaultGradient: ["#64748b", "#334155"] },
    ],
  },
  {
    id: "law-vote",
    name: "选举投票",
    englishName: "Elections & Voting",
    description: "民主选举与民意投票图标",
    icon: "Vote",
    icons: [
      { id: "lvote-1", name: "投票箱", lucideName: "Vote", desc: "选票投入箱中", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "lvote-2", name: "勾选", lucideName: "CheckSquare", desc: "候选人勾选", defaultGradient: ["#10b981", "#047857"] },
      { id: "lvote-3", name: "旗帜", lucideName: "Flag", desc: "竞选宣传旗帜", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "lvote-4", name: "演讲", lucideName: "Megaphone", desc: "竞选公开演讲", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "lvote-5", name: "人群", lucideName: "Users", desc: "选民集会参与", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "lvote-6", name: "统计", lucideName: "BarChart", desc: "票数实时统计", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "lvote-7", name: "饼图", lucideName: "PieChart", desc: "得票比例分析", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "lvote-8", name: "趋势", lucideName: "TrendingUp", desc: "支持率变化", defaultGradient: ["#10b981", "#047857"] },
      { id: "lvote-9", name: "日历", lucideName: "CalendarDays", desc: "投票日安排", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "lvote-10", name: "奖章", lucideName: "Medal", desc: "当选胜利纪念", defaultGradient: ["#eab308", "#ca8a04"] },
    ],
  },
  {
    id: "law-aid",
    name: "维权援助",
    englishName: "Legal Aid",
    description: "法律援助与权益保护图标",
    icon: "HeartHandshake",
    icons: [
      { id: "laid-1", name: "爱心援助", lucideName: "HeartHandshake", desc: "公益法律援助", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "laid-2", name: "咨询", lucideName: "MessageCircle", desc: "在线法律咨询", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "laid-3", name: "电话热线", lucideName: "Phone", desc: "维权热线拨打", defaultGradient: ["#10b981", "#047857"] },
      { id: "laid-4", name: "搜索", lucideName: "Search", desc: "法条案例检索", defaultGradient: ["#64748b", "#334155"] },
      { id: "laid-5", name: "帮助", lucideName: "LifeBuoy", desc: "紧急求助指引", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "laid-6", name: "信息", lucideName: "Info", desc: "权益须知说明", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "laid-7", name: "警告", lucideName: "AlertTriangle", desc: "侵权风险提醒", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "laid-8", name: "禁止", lucideName: "Ban", desc: "违法行为警示", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "laid-9", name: "认证", lucideName: "BadgeCheck", desc: "维权成功认证", defaultGradient: ["#10b981", "#047857"] },
      { id: "laid-10", name: "礼物", lucideName: "Gift", desc: "调解和解赠礼", defaultGradient: ["#ec4899", "#be185d"] },
    ],
  },
  {
    id: "spc-planet",
    name: "行星星系",
    englishName: "Planets & Galaxies",
    description: "太阳系与深空天体图标",
    icon: "Globe",
    icons: [
      { id: "spla-1", name: "地球", lucideName: "Globe", desc: "蓝色家园星球", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "spla-2", name: "地球仪", lucideName: "Globe2", desc: "三维星球模型", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "spla-3", name: "月亮", lucideName: "Moon", desc: "夜空中卫星", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "spla-4", name: "星月", lucideName: "MoonStar", desc: "星月交辉夜空", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "spla-5", name: "太阳", lucideName: "Sun", desc: "恒星能量核心", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "spla-6", name: "星辰", lucideName: "Star", desc: "遥远恒星光芒", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "spla-7", name: "轨道", lucideName: "Orbit", desc: "行星运行轨迹", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "spla-8", name: "原子", lucideName: "Atom", desc: "宇宙微观结构", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "spla-9", name: "彗星", lucideName: "Sparkles", desc: "划过天际彗星", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "spla-10", name: "银河", lucideName: "Sparkles", desc: "璀璨星河星系", defaultGradient: ["#6366f1", "#4f46e5"] },
    ],
  },
  {
    id: "spc-craft",
    name: "航天器",
    englishName: "Spacecraft",
    description: "火箭飞船与空间站图标",
    icon: "Rocket",
    icons: [
      { id: "scrf-1", name: "火箭", lucideName: "Rocket", desc: "运载火箭升空", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "scrf-2", name: "卫星", lucideName: "Satellite", desc: "轨道通信卫星", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "scrf-3", name: "空间站", lucideName: "Box", desc: "近地轨道驻留", defaultGradient: ["#64748b", "#334155"] },
      { id: "scrf-4", name: "探测器", lucideName: "Radar", desc: "深空探测设备", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "scrf-5", name: "燃料罐", lucideName: "Cylinder", desc: "推进剂储存", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "scrf-6", name: "芯片", lucideName: "Cpu", desc: "航天电子核心", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "scrf-7", name: "天线", lucideName: "Radio", desc: "地面信号接收", defaultGradient: ["#10b981", "#047857"] },
      { id: "scrf-8", name: "雷达", lucideName: "Radar", desc: "远程目标追踪", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "scrf-9", name: "电池", lucideName: "Battery", desc: "舱内能源供应", defaultGradient: ["#10b981", "#047857"] },
      { id: "scrf-10", name: "太阳能板", lucideName: "Sun", desc: "光伏发电系统", defaultGradient: ["#f59e0b", "#d97706"] },
    ],
  },
  {
    id: "spc-observe",
    name: "天文观测",
    englishName: "Astronomy",
    description: "望远镜与天文台观测图标",
    icon: "Telescope",
    icons: [
      { id: "sobs-1", name: "望远镜", lucideName: "Telescope", desc: "光学天文观测", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "sobs-2", name: "双筒镜", lucideName: "Binoculars", desc: "野外星空观测", defaultGradient: ["#64748b", "#334155"] },
      { id: "sobs-3", name: "相机", lucideName: "Camera", desc: "深空摄影记录", defaultGradient: ["#64748b", "#334155"] },
      { id: "sobs-4", name: "显微镜", lucideName: "Microscope", desc: "陨石样本分析", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sobs-5", name: "指南针", lucideName: "Compass", desc: "星图方位定位", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "sobs-6", name: "地图", lucideName: "Map", desc: "星图坐标标注", defaultGradient: ["#10b981", "#047857"] },
      { id: "sobs-7", name: "笔记本", lucideName: "Notebook", desc: "观测日志记录", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "sobs-8", name: "时钟", lucideName: "Clock", desc: "观测时间窗口", defaultGradient: ["#64748b", "#334155"] },
      { id: "sobs-9", name: "月亮相位", lucideName: "Moon", desc: "月相变化周期", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "sobs-10", name: "日出", lucideName: "Sunrise", desc: "地平线曙光", defaultGradient: ["#f97316", "#c2410c"] },
    ],
  },
  {
    id: "spc-explore",
    name: "太空探索",
    englishName: "Space Exploration",
    description: "载人航天与行星探测图标",
    icon: "Rocket",
    icons: [
      { id: "sexp-1", name: "发射", lucideName: "Rocket", desc: "点火升空瞬间", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "sexp-2", name: "轨道运行", lucideName: "Orbit", desc: "环绕地球飞行", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sexp-3", name: "着陆", lucideName: "MapPin", desc: "行星表面着陆", defaultGradient: ["#10b981", "#047857"] },
      { id: "sexp-4", name: "漫游车", lucideName: "Car", desc: "外星地表探测", defaultGradient: ["#64748b", "#334155"] },
      { id: "sexp-5", name: "样本", lucideName: "FlaskConical", desc: "采集岩石样本", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "sexp-6", name: "宇航员", lucideName: "User", desc: "载人航天任务", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "sexp-7", name: "团队", lucideName: "Users", desc: "航天任务编队", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "sexp-8", name: "目标", lucideName: "Target", desc: "探测任务目标", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "sexp-9", name: "旗帜", lucideName: "Flag", desc: "登陆点标记", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "sexp-10", name: "奖杯", lucideName: "Trophy", desc: "探索成就荣誉", defaultGradient: ["#f59e0b", "#d97706"] },
    ],
  },
  {
    id: "spc-satellite",
    name: "卫星导航",
    englishName: "Satellite Navigation",
    description: "GPS导航与遥感通信图标",
    icon: "Satellite",
    icons: [
      { id: "ssat-1", name: "导航卫星", lucideName: "Satellite", desc: "全球定位系统", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ssat-2", name: "GPS定位", lucideName: "Navigation", desc: "实时坐标导航", defaultGradient: ["#10b981", "#047857"] },
      { id: "ssat-3", name: "地图定位", lucideName: "MapPinned", desc: "精准地点标记", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ssat-4", name: "路线", lucideName: "Route", desc: "最优路径规划", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "ssat-5", name: "信号", lucideName: "Wifi", desc: "卫星信号强度", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ssat-6", name: "云端", lucideName: "Cloud", desc: "遥感数据上云", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "ssat-7", name: "下载", lucideName: "CloudDownload", desc: "地图数据更新", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "ssat-8", name: "上传", lucideName: "CloudUpload", desc: "遥测数据回传", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "ssat-9", name: "雷达扫描", lucideName: "Radar", desc: "地表遥感扫描", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "ssat-10", name: "链接", lucideName: "Link", desc: "天地链路通信", defaultGradient: ["#64748b", "#334155"] },
    ],
  },
];

export const expandedThemeGroups = [
  {
    "id": "animals",
    "name": "动物与宠物",
    "emoji": "🐾",
    "themeIds": [
      "ani-pets",
      "ani-wild",
      "ani-sea",
      "ani-bird",
      "ani-bug"
    ]
  },
  {
    "id": "architecture",
    "name": "建筑与工程",
    "emoji": "🏗️",
    "themeIds": [
      "bld-landmark",
      "bld-construct",
      "bld-interior",
      "bld-urban",
      "bld-infra"
    ]
  },
  {
    "id": "fashion",
    "name": "时尚美妆",
    "emoji": "👗",
    "themeIds": [
      "fsh-cloth",
      "fsh-access",
      "fsh-beauty",
      "fsh-shoes",
      "fsh-trend"
    ]
  },
  {
    "id": "farm",
    "name": "农业田园",
    "emoji": "🌾",
    "themeIds": [
      "frm-crop",
      "frm-garden",
      "frm-tool",
      "frm-livestock",
      "frm-rural"
    ]
  },
  {
    "id": "law",
    "name": "法律政务",
    "emoji": "⚖️",
    "themeIds": [
      "law-doc",
      "law-gov",
      "law-justice",
      "law-vote",
      "law-aid"
    ]
  },
  {
    "id": "space",
    "name": "天文航天",
    "emoji": "🚀",
    "themeIds": [
      "spc-planet",
      "spc-craft",
      "spc-observe",
      "spc-explore",
      "spc-satellite"
    ]
  }
];

export const expandedThemeEmoji: Record<string, string> = {
  "ani-pets": "🐱",
  "ani-wild": "🌲",
  "ani-sea": "🐟",
  "ani-bird": "🦅",
  "ani-bug": "🐛",
  "bld-landmark": "🏛️",
  "bld-construct": "🔨",
  "bld-interior": "🛋️",
  "bld-urban": "🗺️",
  "bld-infra": "🔌",
  "fsh-cloth": "👔",
  "fsh-access": "💎",
  "fsh-beauty": "💄",
  "fsh-shoes": "👟",
  "fsh-trend": "📸",
  "frm-crop": "🌽",
  "frm-garden": "🌸",
  "frm-tool": "🚜",
  "frm-livestock": "🥚",
  "frm-rural": "🏞️",
  "law-doc": "📜",
  "law-gov": "🏛️",
  "law-justice": "⚖️",
  "law-vote": "🗳️",
  "law-aid": "🤝",
  "spc-planet": "🪐",
  "spc-craft": "🚀",
  "spc-observe": "🔭",
  "spc-explore": "🌌",
  "spc-satellite": "📡"
};
