/** 社交与媒体、创意与娱乐 — 各拓展 4 子分类 × 10 图标 */
export const socialCreativeThemesData = [
  {
    id: "soc-forum",
    name: "社区论坛",
    englishName: "Community Forum",
    description: "帖子讨论与社区互动图标",
    icon: "MessagesSquare",
    icons: [
      { id: "sfrm-1", name: "话题帖", lucideName: "MessagesSquare", desc: "热门讨论主题帖", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "sfrm-2", name: "回复楼", lucideName: "MessageSquareReply", desc: "楼层回复互动", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "sfrm-3", name: "置顶公告", lucideName: "Pin", desc: "版主置顶通知", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "sfrm-4", name: "版主徽章", lucideName: "Badge", desc: "社区管理员标识", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "sfrm-5", name: "点赞支持", lucideName: "ThumbsUp", desc: "赞同优质内容", defaultGradient: ["#10b981", "#047857"] },
      { id: "sfrm-6", name: "收藏帖子", lucideName: "Bookmark", desc: "稍后阅读收藏", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sfrm-7", name: "标签分类", lucideName: "Tags", desc: "话题标签归档", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "sfrm-8", name: "搜索帖子", lucideName: "Search", desc: "全文检索历史", defaultGradient: ["#64748b", "#334155"] },
      { id: "sfrm-9", name: "举报屏蔽", lucideName: "ShieldAlert", desc: "违规内容处理", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "sfrm-10", name: "用户头像", lucideName: "CircleUser", desc: "社区成员资料", defaultGradient: ["#ec4899", "#be185d"] },
    ],
  },
  {
    id: "soc-live",
    name: "直播互动",
    englishName: "Live Streaming",
    description: "实时直播与观众互动图标",
    icon: "Radio",
    icons: [
      { id: "sliv-1", name: "直播中", lucideName: "Radio", desc: "实时信号播出", defaultGradient: ["#ef4444", "#b91c1c"], defaultBadge: "LIVE" },
      { id: "sliv-2", name: "视频画面", lucideName: "Video", desc: "高清直播推流", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sliv-3", name: "弹幕评论", lucideName: "MessageSquare", desc: "实时弹幕互动", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "sliv-4", name: "礼物打赏", lucideName: "Gift", desc: "观众礼物支持", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "sliv-5", name: "爱心点赞", lucideName: "Heart", desc: "直播间点赞", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "sliv-6", name: "观众人数", lucideName: "Users", desc: "在线观看统计", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "sliv-7", name: "分享直播间", lucideName: "Share2", desc: "邀请好友观看", defaultGradient: ["#10b981", "#047857"] },
      { id: "sliv-8", name: "麦克风", lucideName: "Mic", desc: "主播语音解说", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "sliv-9", name: "摄像头", lucideName: "Webcam", desc: "镜头实时采集", defaultGradient: ["#64748b", "#334155"] },
      { id: "sliv-10", name: "录屏回放", lucideName: "MonitorPlay", desc: "直播录像回看", defaultGradient: ["#6366f1", "#4f46e5"] },
    ],
  },
  {
    id: "soc-podcast",
    name: "播客电台",
    englishName: "Podcast & Radio",
    description: "音频节目与电台收听图标",
    icon: "Podcast",
    icons: [
      { id: "spod-1", name: "播客节目", lucideName: "Podcast", desc: "订阅音频节目", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "spod-2", name: "电台广播", lucideName: "Radio", desc: "调频电台收听", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "spod-3", name: "耳机收听", lucideName: "Headphones", desc: "私密沉浸聆听", defaultGradient: ["#64748b", "#334155"] },
      { id: "spod-4", name: "播放列表", lucideName: "ListMusic", desc: "节目单顺序播放", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "spod-5", name: "单曲循环", lucideName: "Repeat", desc: "重复播放模式", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "spod-6", name: "随机播放", lucideName: "Shuffle", desc: "打乱节目顺序", defaultGradient: ["#10b981", "#047857"] },
      { id: "spod-7", name: "音量调节", lucideName: "Volume2", desc: "声音大小控制", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "spod-8", name: "下载离线", lucideName: "Download", desc: "缓存节目离线", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "spod-9", name: "节目封面", lucideName: "Disc", desc: "专辑封面展示", defaultGradient: ["#1e293b", "#0f172a"] },
      { id: "spod-10", name: "主持人", lucideName: "Mic2", desc: "主播嘉宾访谈", defaultGradient: ["#f43f5e", "#be123c"] },
    ],
  },
  {
    id: "soc-creator",
    name: "内容创作",
    englishName: "Content Creation",
    description: "自媒体与短视频创作图标",
    icon: "Sparkles",
    icons: [
      { id: "scr8-1", name: "创意火花", lucideName: "Sparkles", desc: "灵感创作起点", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "scr8-2", name: "短视频", lucideName: "Clapperboard", desc: "竖屏短片拍摄", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "scr8-3", name: "文案编辑", lucideName: "Type", desc: "标题正文撰写", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "scr8-4", name: "封面设计", lucideName: "Image", desc: "吸睛封面制作", defaultGradient: ["#10b981", "#047857"] },
      { id: "scr8-5", name: "数据增长", lucideName: "TrendingUp", desc: "粉丝播放增长", defaultGradient: ["#10b981", "#047857"], defaultBadge: "UP" },
      { id: "scr8-6", name: "话题标签", lucideName: "Hash", desc: "热门话题标记", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "scr8-7", name: "定时发布", lucideName: "CalendarClock", desc: "预约发布时间", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "scr8-8", name: "素材库", lucideName: "FolderOpen", desc: "创作素材管理", defaultGradient: ["#64748b", "#334155"] },
      { id: "scr8-9", name: "剪辑时间轴", lucideName: "LayoutList", desc: "视频剪辑编排", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "scr8-10", name: "粉丝互动", lucideName: "HeartHandshake", desc: "与粉丝建立连接", defaultGradient: ["#f43f5e", "#be123c"] },
    ],
  },
  {
    id: "cre-music",
    name: "音乐演奏",
    englishName: "Music Performance",
    description: "乐器演奏与音乐创作图标",
    icon: "Music",
    icons: [
      { id: "cmus-1", name: "音符旋律", lucideName: "Music", desc: "乐谱旋律创作", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "cmus-2", name: "钢琴键盘", lucideName: "Piano", desc: "键盘乐器演奏", defaultGradient: ["#64748b", "#334155"] },
      { id: "cmus-3", name: "吉他弹奏", lucideName: "Guitar", desc: "弦乐指弹伴奏", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "cmus-4", name: "架子鼓", lucideName: "Drum", desc: "节奏打击乐器", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "cmus-5", name: "演唱会", lucideName: "MicVocal", desc: "现场声乐演唱", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "cmus-6", name: "乐谱笔记", lucideName: "Notebook", desc: "手写谱面记录", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "cmus-7", name: "混音台", lucideName: "SlidersHorizontal", desc: "音轨均衡调节", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "cmus-8", name: "耳机监听", lucideName: "Headphones", desc: "录音棚监听", defaultGradient: ["#64748b", "#334155"] },
      { id: "cmus-9", name: "黑胶唱片", lucideName: "Disc", desc: "复古唱片播放", defaultGradient: ["#1e293b", "#0f172a"] },
      { id: "cmus-10", name: "节拍器", lucideName: "Timer", desc: "练习节奏把控", defaultGradient: ["#06b6d4", "#0891b2"] },
    ],
  },
  {
    id: "cre-photo",
    name: "摄影影像",
    englishName: "Photography",
    description: "摄影拍摄与后期处理图标",
    icon: "Camera",
    icons: [
      { id: "cpho-1", name: "单反相机", lucideName: "Camera", desc: "专业摄影机身", defaultGradient: ["#64748b", "#334155"] },
      { id: "cpho-2", name: "镜头变焦", lucideName: "ZoomIn", desc: "远近焦段切换", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "cpho-3", name: "闪光灯", lucideName: "Zap", desc: "补光闪光拍摄", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "cpho-4", name: "相册图库", lucideName: "Images", desc: "照片批量管理", defaultGradient: ["#10b981", "#047857"] },
      { id: "cpho-5", name: "滤镜调色", lucideName: "Palette", desc: "色调风格渲染", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "cpho-6", name: "裁剪构图", lucideName: "Crop", desc: "画面比例调整", defaultGradient: ["#64748b", "#334155"] },
      { id: "cpho-7", name: "对焦框", lucideName: "Scan", desc: "精准对焦区域", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "cpho-8", name: "延时摄影", lucideName: "Clock", desc: "长曝光慢门", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "cpho-9", name: "全景拍摄", lucideName: "Maximize2", desc: "宽幅场景记录", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "cpho-10", name: "导出分享", lucideName: "Share2", desc: "成片发布传播", defaultGradient: ["#8b5cf6", "#6d28d9"] },
    ],
  },
  {
    id: "cre-craft",
    name: "手工DIY",
    englishName: "Crafts & DIY",
    description: "手工制作与创意手作图标",
    icon: "Scissors",
    icons: [
      { id: "ccrf-1", name: "剪刀裁剪", lucideName: "Scissors", desc: "布料纸张裁切", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "ccrf-2", name: "胶水粘合", lucideName: "Droplet", desc: "手工胶合固定", defaultGradient: ["#38bdf8", "#0284c7"] },
      { id: "ccrf-3", name: "针线缝纫", lucideName: "Pen", desc: "刺绣缝纫工艺", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "ccrf-4", name: "颜料上色", lucideName: "Paintbrush", desc: "手绘涂色装饰", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "ccrf-5", name: "木工雕刻", lucideName: "Hammer", desc: "木器敲打塑形", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "ccrf-6", name: "折纸造型", lucideName: "Origami", desc: "纸张折叠艺术", defaultGradient: ["#10b981", "#047857"] },
      { id: "ccrf-7", name: "陶艺塑形", lucideName: "Cylinder", desc: "陶泥手工成型", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "ccrf-8", name: "编织毛线", lucideName: "Ribbon", desc: "针织编织作品", defaultGradient: ["#f43f5e", "#be123c"] },
      { id: "ccrf-9", name: "工具箱", lucideName: "Briefcase", desc: "手作工具收纳", defaultGradient: ["#64748b", "#334155"] },
      { id: "ccrf-10", name: "成品展示", lucideName: "Package", desc: "手作礼物包装", defaultGradient: ["#f59e0b", "#d97706"] },
    ],
  },
  {
    id: "cre-show",
    name: "演出表演",
    englishName: "Performance & Show",
    description: "舞台演出与文艺表演图标",
    icon: "Theater",
    icons: [
      { id: "cshw-1", name: "戏剧舞台", lucideName: "Theater", desc: "剧场舞台表演", defaultGradient: ["#8b5cf6", "#6d28d9"] },
      { id: "cshw-2", name: "马戏帐篷", lucideName: "Tent", desc: "巡回马戏演出", defaultGradient: ["#ef4444", "#b91c1c"] },
      { id: "cshw-3", name: "魔术表演", lucideName: "Wand", desc: "魔术道具变幻", defaultGradient: ["#6366f1", "#4f46e5"] },
      { id: "cshw-4", name: "舞蹈律动", lucideName: "Activity", desc: "肢体舞蹈节奏", defaultGradient: ["#ec4899", "#be185d"] },
      { id: "cshw-5", name: "喜剧笑脸", lucideName: "Smile", desc: "脱口秀欢乐", defaultGradient: ["#f59e0b", "#d97706"] },
      { id: "cshw-6", name: "Tickets入场", lucideName: "Ticket", desc: "演出门票检票", defaultGradient: ["#f97316", "#c2410c"] },
      { id: "cshw-7", name: "舞台灯光", lucideName: "Zap", desc: "追光氛围照明", defaultGradient: ["#eab308", "#ca8a04"] },
      { id: "cshw-8", name: "观众席", lucideName: "Users", desc: "台下观众互动", defaultGradient: ["#06b6d4", "#0891b2"] },
      { id: "cshw-9", name: "节目单", lucideName: "ClipboardList", desc: "演出流程安排", defaultGradient: ["#3b82f6", "#1d4ed8"] },
      { id: "cshw-10", name: "谢幕奖杯", lucideName: "Trophy", desc: "表演荣誉嘉奖", defaultGradient: ["#f59e0b", "#d97706"] },
    ],
  },
];

export const socialCreativeThemeEmoji: Record<string, string> = {
  "soc-forum": "💭",
  "soc-live": "🔴",
  "soc-podcast": "🎙️",
  "soc-creator": "✨",
  "cre-music": "🎵",
  "cre-photo": "📷",
  "cre-craft": "✂️",
  "cre-show": "🎭"
};

export const socialCreativeGroupThemeIds: Record<string, string[]> = {
  "connect": [
    "soc-forum",
    "soc-live",
    "soc-podcast",
    "soc-creator"
  ],
  "creative": [
    "cre-music",
    "cre-photo",
    "cre-craft",
    "cre-show"
  ]
};
